### ISSUE TITLE
RuntimeError: No available targets are compatible with triple "arm-unknown-linux-gnu"

### ISSUE THREAD

**Issue by igallta2** [numba/llvmlite#1039]
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/树莓派代码/test/树莓派代码/fall.py", line 8, in <module>
    from oob_parser import uartParserSDK
  File "/home/pi/.virtualenvs/树莓派代码/test/树莓派代码/oob_parser.py", line 11, in <module>
    from tsfresh.feature_extraction.feature_calculators import time_reversal_asymmetry_statistic
  File "/home/pi/.local/lib/python3.9/site-packages/tsfresh/__init__.py", line 27, in <module>
    from tsfresh.convenience.relevant_extraction import (  # noqa: E402
  File "/home/pi/.local/lib/python3.9/site-packages/tsfresh/convenience/relevant_extraction.py", line 8, in <module>
    from tsfresh.feature_extraction import extract_features
  File "/home/pi/.local/lib/python3.9/site-packages/tsfresh/feature_extraction/__init__.py", line 5, in <module>
    from tsfresh.feature_extraction.extraction import extract_features
  File "/home/pi/.local/lib/python3.9/site-packages/tsfresh/feature_extraction/extraction.py", line 15, in <module>
    from tsfresh.feature_extraction import feature_calculators
  File "/home/pi/.local/lib/python3.9/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 28, in <module>
    import stumpy
  File "/home/pi/.local/lib/python3.9/site-packages/stumpy/__init__.py", line 6, in <module>
    from .aamp import aamp  # noqa: F401
  File "/home/pi/.local/lib/python3.9/site-packages/stumpy/aamp.py", line 9, in <module>
    from . import config, core
  File "/home/pi/.local/lib/python3.9/site-packages/stumpy/core.py", line 593, in <module>
    def _sliding_dot_product(Q, T):
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/decorators.py", line 225, in wrapper
    disp = dispatcher(py_func=func, locals=locals,
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 818, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/registry.py", line 30, in target_context
    return self._toplevel_target_context
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/utils.py", line 781, in __get__
    return super().__get__(*args, **kwargs)
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/registry.py", line 18, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context, self._target_name)
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/cpu.py", line 42, in __init__
    super().__init__(typingctx, target)
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/base.py", line 254, in __init__
    self.init()
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/cpu.py", line 51, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/codegen.py", line 1171, in __init__
    self._init(self._llvm_module)
  File "/home/pi/.local/lib/python3.9/site-packages/numba/core/codegen.py", line 1176, in _init
    target = ll.Target.from_triple(ll.get_process_triple())
  File "/home/pi/.local/lib/python3.9/site-packages/llvmlite/binding/targets.py", line 197, in from_triple
    raise RuntimeError(str(outerr))
RuntimeError: No available targets are compatible with triple "arm-unknown-linux-gnu"

**Comment by gmarkall** [comment]
How did you install Numba and llvmlite? Where does your LLVM come from?

**Comment by igallta2** [comment]
The problem has been solved. After upgrading the Raspberry Pi system to 64-bit, I can use the normal "pip install" command.

**Comment by igallta2** [comment]
I downloaded "Numba" and "llvmlite" manually from the browser before, so they don't match.

**Comment by gmarkall** [comment]
Thanks for the update - closing this issue as it appears to be resolved.
