### ISSUE TITLE
How to solve: Issue with `llvmlite` installation in Termux due to LLVM version mismatch 

### ISSUE THREAD

**Issue by Manamama** [numba/llvmlite#1061]
{I keep forgetting how I had solved it the last time and then I muck around with update alternatives or even the code, so below a quick aide memoire for fellow Termux etc. users, so that LLMs also find it ;). 👾}

I encountered an issue while trying to install `llvmlite` in Termux on Android. The installation process failed with the following error:

```
Running command python setup.py bdist_wheel
running bdist_wheel
/data/data/com.termux/files/usr/bin/python3.11 /data/data/com.termux/files/usr/tmp/pip-install-w_763fna/llvmlite_6e1d481a0a084583b02af4b1d34ee322/ffi/build.py
LLVM version... 18.1.7
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/tmp/pip-install-w_763fna/llvmlite_6e1d481a0a084583b02af4b1d34ee322/ffi/build.py", line 235, in <module>
    main()
  File "/data/data/com.termux/files/usr/tmp/pip-install-w_763fna/llvmlite_6e1d481a0a084583b02af4b1d34ee322/ffi/build.py", line 225, in main
    main_posix('linux', '.so')
  File "/data/data/com.termux/files/usr/tmp/pip-install-w_763fna/llvmlite_6e1d481a0a084583b02af4b1d34ee322/ffi/build.py", line 181, in main_posix
    raise RuntimeError(msg)
```

It seems that `llvmlite` requires LLVM 14, but the default LLVM version in Termux is 18.1.7.

To resolve this issue, I installed LLVM 14 from the Termux repository using `pkg install llvm-14` (`llvm-14/tur-packages,now 13.0.1-2 aarch64`). Then, I set the `LLVM_CONFIG` environment variable to point to the `llvm-config` executable for LLVM 14:

```bash
export LLVM_CONFIG=/data/data/com.termux/files/usr/opt/libllvm-14/bin/llvm-config
```

After setting the `LLVM_CONFIG` environment variable, I was able to install `llvmlite` successfully.

I'm reporting this issue to help others who might encounter the same problem. It might be helpful to mention the requirement for LLVM 14 and the workaround in the `llvmlite` installation instructions for Termux.🧾🖲️

**Comment by kc611** [comment]
Thank you @Manamama for reporting this behaviour. I'm marking this as documentation for now.

**Comment by kc611** [comment]
Closing because the procedure is already documented in the llvmlite documentation.

**Comment by sklam** [comment]
It's explained at https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvmlite

**Comment by Manamama** [comment]
Quick and somehow messy further explanation, ping @kc611 . 
Indeed, it is explained, and you and I know the root cause (this: https://github.com/numba/llvmlite/issues/1062#issuecomment-2172966134 one), but think also how it looks for the end user. 

If a random tts module requires llvmlite, then this is how it looks in the terminal :

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/ffi.py", line 136, in __getattr__
    return self._fntab[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'LLVMPY_AddSymbol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/ffi.py", line 117, in _load_lib
    self._lib_handle = ctypes.CDLL(str(lib_path))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen failed: library "libLLVM-14.so" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/libllvmlite.so in namespace (default)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/TTS/bin/synthesize.py", line 338, in main
    from TTS.api import TTS
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/TTS/api.py", line 9, in <module>
    from TTS.utils.audio.numpy_transforms import save_wav
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/TTS/utils/audio/__init__.py", line 1, in <module>
    from TTS.utils.audio.processor import AudioProcessor
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/TTS/utils/audio/processor.py", line 10, in <module>
    from TTS.utils.audio.numpy_transforms import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/TTS/utils/audio/numpy_transforms.py", line 8, in <module>
    from librosa import magphase, pyin
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/lazy_loader/__init__.py", line 83, in __getattr__
    attr = getattr(submod, name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/lazy_loader/__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/librosa/core/spectrum.py", line 13, in <module>
    from numba import jit
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numba/__init__.py", line 73, in <module>
    from numba.core import config
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/numba/core/config.py", line 17, in <module>
    import llvmlite.binding as ll
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/dylib.py", line 36, in <module>
    ffi.lib.LLVMPY_AddSymbol.argtypes = [
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/ffi.py", line 139, in __getattr__
    cfn = getattr(self._lib, name)
                  ^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/ffi.py", line 131, in _lib
    self._load_lib()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/ffi.py", line 125, in _load_lib
    raise OSError("Could not find/load shared object file") from e
OSError: Could not find/load shared object file

```


The "naive" end user fails to notice the importance of the "libLLVM-14.so" bit there and thinks to themselves: "OK, I will just force reinstall llvmlite, surely it will pull up something missing as submodule". 

 Surprisingly, it "works" (while I guess - it should not):

```
pip install -U -v  --force-reinstall llvmlite
Using pip 24.1 from /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip (python 3.11)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
  Link requires a different Python (3.11.9 not in: '>=3.6,<3.10'): https://files.pythonhosted.org/packages/19/66/6b2c49c7c68da48d17059882fdb9ad9ac9e5ac3f22b00874d7996e3c44a8/llvmlite-0.36.0.tar.gz (from https://pypi.org/simple/llvmlite/) (requires-python:>=3.6,<3.10)
  Link requires a different Python (3.11.9 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/55/21/f7df5d35f3f5d0637d64a89f6b0461f2adf78e22916d6372486f8fc2193d/llvmlite-0.37.0.tar.gz (from https://pypi.org/simple/llvmlite/) (requires-python:>=3.7,<3.10)
  Link requires a different Python (3.11.9 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/d8/e3/bd329a96549809598acd5daaccd35fd9d0883185cfe7f681a9e3e54beaa0/llvmlite-0.38.0.tar.gz (from https://pypi.org/simple/llvmlite/) (requires-python:>=3.7,<3.11)
  Link requires a different Python (3.11.9 not in: '>=3.7,<3.11'): https://files.pythonhosted.org/packages/90/fc/313c916fb49495ac7c1f9ab213cd3d3285342691b860a2810a51c6c1a10e/llvmlite-0.38.1.tar.gz (from https://pypi.org/simple/llvmlite/) (requires-python:>=3.7,<3.11)
Collecting llvmlite
  Using cached llvmlite-0.43.0-cp311-cp311-linux_aarch64.whl
Installing collected packages: llvmlite
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.43.0
    Uninstalling llvmlite-0.43.0:
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite-0.43.0.dist-info/
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/__init__.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/__pycache__/
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/_version.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/binding/
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/ir/
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__init__.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__main__.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/__init__.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/__main__.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/customize.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/refprune_proto.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/test_binding.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/test_ir.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/test_refprune.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/__pycache__/test_valuerepr.cpython-311.pyc
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/customize.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/refprune_proto.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/test_binding.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/test_ir.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/test_refprune.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/tests/test_valuerepr.py
      Removing file or directory /data/data/com.termux/files/usr/lib/python3.11/site-packages/llvmlite/utils.py
      Successfully uninstalled llvmlite-0.43.0
Successfully installed llvmlite-0.43.0

```
despite there being no llvm-14 (as I had removed it, just to show yous):

```
~ $ apt list | grep llvm-

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libllvm-11/tur-packages 11.1.0-1 aarch64
libllvm-13/tur-packages 13.0.1-2 aarch64
libllvm-14/tur-packages 14.0.6 aarch64
libllvm-15/tur-packages 15.0.7-1 aarch64
libllvm-16-static/tur-packages 20220907 aarch64
libllvm-16/tur-packages 1:16.0.6-1 aarch64
libllvm-classic-flang/tur-packages,now 20230419-3 aarch64 [installed,automatic]
libllvm-codon/tur-packages,now 20221023-3 aarch64 [installed]
libllvm-glibc-static/glibc 18.1.7 aarch64
libllvm-glibc/glibc,now 18.1.7 aarch64 [installed,automatic]
libllvm-julia/termux 6.0.1 aarch64
libllvm-static/stable 18.1.7-1 aarch64
llvm-11/tur-packages 11.1.0-1 aarch64
llvm-13/tur-packages 13.0.1-2 aarch64
llvm-14/tur-packages 14.0.6 aarch64
llvm-15/tur-packages 15.0.7-1 aarch64
llvm-16/tur-packages 1:16.0.6-1 aarch64
llvm-glibc/glibc,now 18.1.7 aarch64 [installed]
llvm-libunwind-dev/termux 8.0.0 aarch64
llvm-libunwind/termux 8.0.0 aarch64
llvm-mingw-w64-libcompiler-rt/stable 20240417 all
llvm-mingw-w64-tools/stable 11.0.0 aarch64
llvm-mingw-w64-ucrt/stable 20240417 all
llvm-mingw-w64/stable 20240417 all
llvm-tools-16/tur-packages 1:16.0.6-1 aarch64
llvm-tools/stable 18.1.7-1 aarch64
spirv-llvm-translator-glibc-static/glibc 17.0.0 aarch64
spirv-llvm-translator-glibc/glibc 18.1.0 aarch64
~ $ 
```

The actual "trick" is to re-re-reinstall llvm-14 there  as I had written, not trying in vain to fix anything in your llvmlite via pip only. (OK, one can also make it work with newer llvms, as we both know, but then it causes some new even sneakier errors). 

Alas, the newest flang is incompatible with the old llvm-14 for some recondite reason:

```
~ $ apt list | grep flang

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

classic-flang/tur-packages,now 20230520 aarch64 [installed]
flang-16/tur-packages 20220907-1 aarch64
flang/stable 18.1.7 aarch64
libllvm-classic-flang/tur-packages,now 20230419-3 aarch64 [installed,automatic]
~ $ 

~ $ apt install flang
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 flang : Depends: libllvm (= 18.1.7) but 18.1.7-1 is to be installed
         Depends: clang (= 18.1.7) but 18.1.7-1 is to be installed
         Depends: lld (= 18.1.7) but 18.1.7-1 is to be installed
         Depends: mlir (= 18.1.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
~ $ 
```

so one must use `classic-flang` there, which is in turn incompatible with llvm-14, thus also with llvmlite , but that is yet another story. 
OK, let me also show that story as it is relevant to llvmlite to a minute extent:
```
~ $ apt install llvm-14
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  binutils libllvm-14
The following packages will be REMOVED:
  binutils-is-llvm classic-flang libllvm-classic-flang
The following NEW packages will be installed:
  binutils libllvm-14 llvm-14
0 upgraded, 3 newly installed, 3 to remove and 23 not upgraded.
Need to get 0 B/60.6 MB of archives.
After this operation, 386 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 171260 files and directories currently installed.)
Removing classic-flang (20230520) ...
Removing libllvm-classic-flang (20230419-3) ...
dpkg: binutils-is-llvm: dependency problems, but removing anyway as you requested:
 termux-apt-repo depends on binutils-is-llvm | binutils; however:
  Package binutils-is-llvm is to be removed.
  Package binutils is not installed.

Removing binutils-is-llvm (0.3-3) ...
Selecting previously unselected package binutils.
(Reading database ... 167827 files and directories currently installed.)
Preparing to unpack .../binutils_2.42_aarch64.deb ...
Unpacking binutils (2.42) ...
Selecting previously unselected package libllvm-14.
Preparing to unpack .../libllvm-14_14.0.6_aarch64.deb ...
Unpacking libllvm-14 (14.0.6) ...
Selecting previously unselected package llvm-14.
Preparing to unpack .../llvm-14_14.0.6_aarch64.deb ...
Unpacking llvm-14 (14.0.6) ...
Setting up binutils (2.42) ...
Setting up libllvm-14 (14.0.6) ...
Setting up llvm-14 (14.0.6) ...
~ $ 

```
so now `time python   /data/data/com.termux/files/usr/bin/tts` kinda works with llvmlite, but then of course it rightly complains  that `  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 50, in <module>
    from . import _arpack
ImportError: dlopen failed: library "libflang.so" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-311.so in namespace (default)` , which is in turn solvable by ugly copying the flang libs and `export LD_LIBRARY_PATH="/data/data/com.termux/files/home/.local/lib:/data/data/com.termux/files/usr/opt/classic-flang.bak/lib"` in very short. 

So, once again, the end-user errors as above are too cryptic, so I had added the above `quick aide memoire for fellow Termux etc. users, so that LLMs also find it ;). 👾}` , which surprisingly, they do well, especially Ms Perplexity AI.

**Comment by Manamama** [comment]
Update: I have removed one third in the above - about the the oldish flang (sic) kvetching about llvm-14, as now the newer flang is compatible with llvm-14, hence also with llvmlite itself:
`~ $ apt install flang
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  mlir
The following NEW packages will be installed:
  flang mlir
0 upgraded, 2 newly installed, 0 to remove and 31 not upgraded.
Need to get 42.3 MB/91.6 MB of archives.
After this operation, 1212 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
`  etc.

**Comment by Manamama** [comment]
FYI, my advice seems to be out of date , as: 
```
~/.../ffi/build $ export LLVM_DIR=/data/data/com.termux/files/usr/opt/libllvm-14/lib/cmake/llvm                                                                   export LLVM_CONFIG=/data/data/com.termux/files/usr/opt/libllvm-14/bin/llvm-config~/.../ffi/build $ cmake .                                                        -- Performing Test Terminfo_LINKABLE                                             -- Performing Test Terminfo_LINKABLE - Success                                   -- Found Terminfo: /data/data/com.termux/files/usr/lib/libtinfo.so               -- Found LLVM 14.0.6                                                             -- Using LLVMConfig.cmake in: /data/data/com.termux/files/usr/opt/libllvm-14/lib/cmake/llvm                                                                       CMake Error at CMakeLists.txt:46 (message):                                        LLVM CMake export states LLVM version is 14, llvmlite only officially            supports 20.                                                                                                                                                                                                                                     -- Configuring incomplete, errors occurred!                                      ~/.../ffi/build
```
That is: `llvmlite only officially            supports 20`
