### ISSUE TITLE
/usr/bin/ld: cannot find -ledit

### ISSUE THREAD

**Issue by nooperpudd** [numba/llvmlite#120]
```
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /root/.virtualenvs/wealthfof/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c151v809/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp2zbi13rtpip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  got version from file /tmp/pip-build-c151v809/llvmlite/llvmlite/_version.py {'version': '0.8.0', 'full': 'cb57c3dc90efd291822e07839caee2cfebfff5d4'}
  running build_ext
  /root/.virtualenvs/wealthfof/bin/python3.4 /tmp/pip-build-c151v809/llvmlite/ffi/build.py
  LLVM version... 3.6.0
  # static-libstdc++ avoids runtime dependencies on a
  # particular libstdc++ version.
  g++ -static-libstdc++ -shared -flto `llvm-config --cxxflags` -fno-rtti -g assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -flto `llvm-config --ldflags` -Wl,--exclude-libs=ALL `llvm-config --system-libs --libs all`
  /usr/bin/ld: cannot find -ledit
  collect2: error: ld returned 1 exit status
  make: *** [libllvmlite.so] Error 1
  Traceback (most recent call last):
    File "/tmp/pip-build-c151v809/llvmlite/ffi/build.py", line 114, in <module>
      main()
    File "/tmp/pip-build-c151v809/llvmlite/ffi/build.py", line 104, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-c151v809/llvmlite/ffi/build.py", line 96, in main_posix
      subprocess.check_call(['make', '-f', makefile])
    File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
```

**Comment by pitrou** [comment]
This is documented: http://llvmlite.pydata.org/en/latest/install/index.html#prerequisites-unix

> If building LLVM on Ubuntu, the linker may report an error if the development version of libedit is not installed. Install libedit-dev if you run into this problem.

**Comment by acidjazz** [comment]
`sudo yum install libedit-devel` not libedit-dev
