### ISSUE TITLE
Can't build llvmlite, missing LLVMOProfileJIT

### ISSUE THREAD

**Issue by krey** [numba/llvmlite#150]
I'm trying to install llvmlite on ArchLinux using llvm 3.7 and I get an error about not being able to link LLVMOProfileJIT. I downgraded to llvm 3.5 and I get a different error now:

```
    assembly.cpp: In function ‘LLVMOpaqueModule* LLVMPY_ParseAssembly(LLVMContextRef, const char*, const char**)’:
    assembly.cpp:25:64: error: ‘parseAssemblyString’ was not declared in this scope
         Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();
                                                                    ^
    bitcode.cpp: In function ‘void LLVMPY_WriteBitcodeToString(LLVMModuleRef, const char**, size_t*)’:
    bitcode.cpp:13:62: error: ‘LLVMWriteBitcodeToMemoryBuffer’ was not declared in this scope
         LLVMMemoryBufferRef MB = LLVMWriteBitcodeToMemoryBuffer(M);
                                                                  ^
    core.cpp: In function ‘void LLVMPY_SetCommandLine(const char*, const char*)’:
    core.cpp:36:46: error: ‘LLVMParseCommandLineOptions’ was not declared in this scope
         LLVMParseCommandLineOptions(2, argv, NULL);
                                                  ^
    module.cpp: In function ‘LLVMOpaqueModule* LLVMPY_CloneModule(LLVMModuleRef)’:
    module.cpp:223:29: error: ‘LLVMCloneModule’ was not declared in this scope
         return LLVMCloneModule(M);
                                 ^
    executionengine.cpp: In function ‘LLVMOpaqueExecutionEngine* create_execution_engine(LLVMModuleRef, LLVMTargetMachineRef, char**)’:
    executionengine.cpp:72:74: error: no matching function for call to ‘llvm::EngineBuilder::EngineBuilder(std::unique_ptr<llvm::Module>)’
         llvm::EngineBuilder eb(std::unique_ptr<llvm::Module>(llvm::unwrap(M)));
                                                                              ^
    In file included from executionengine.cpp:6:0:
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:594:3: note: candidate: llvm::EngineBuilder::EngineBuilder(llvm::Module*)
       EngineBuilder(Module *m) : M(m) {
       ^
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:594:3: note:   no known conversion for argument 1 from ‘std::unique_ptr<llvm::Module>’ to ‘llvm::Module*’
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate: llvm::EngineBuilder::EngineBuilder(const llvm::EngineBuilder&)
     class EngineBuilder {
           ^
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note:   no known conversion for argument 1 from ‘std::unique_ptr<llvm::Module>’ to ‘const llvm::EngineBuilder&’
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate: llvm::EngineBuilder::EngineBuilder(llvm::EngineBuilder&&)
    /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note:   no known conversion for argument 1 from ‘std::unique_ptr<llvm::Module>’ to ‘llvm::EngineBuilder&&’
    executionengine.cpp: In function ‘uint64_t LLVMPY_GetGlobalValueAddress(LLVMExecutionEngineRef, const char*)’:
    executionengine.cpp:107:46: error: ‘LLVMGetGlobalValueAddress’ was not declared in this scope
         return LLVMGetGlobalValueAddress(EE, Name);
                                                  ^
    executionengine.cpp: In function ‘uint64_t LLVMPY_GetFunctionAddress(LLVMExecutionEngineRef, const char*)’:
    executionengine.cpp:114:43: error: ‘LLVMGetFunctionAddress’ was not declared in this scope
         return LLVMGetFunctionAddress(EE, Name);
                                               ^
    executionengine.cpp: At global scope:
    executionengine.cpp:187:45: error: ‘llvm::MemoryBufferRef’ has not been declared
                                           llvm::MemoryBufferRef MBR)
                                                 ^
    executionengine.cpp:200:49: error: conflicting return type specified for ‘virtual std::unique_ptr<llvm::MemoryBuffer> LLVMPYObjectCache::getObject(const llvm::Module*)’
         virtual std::unique_ptr<llvm::MemoryBuffer> getObject(const llvm::Module* M)
                                                     ^
    In file included from executionengine.cpp:8:0:
    /usr/include/llvm/ExecutionEngine/ObjectCache.h:36:25: error:   overriding ‘virtual llvm::MemoryBuffer* llvm::ObjectCache::getObject(const llvm::Module*)’
       virtual MemoryBuffer* getObject(const Module* M) = 0;
                             ^
    /usr/include/llvm/ExecutionEngine/ObjectCache.h:30:16: warning: ‘virtual void llvm::ObjectCache::notifyObjectCompiled(const llvm::Module*, const llvm::MemoryBuffer*)’ was hidden [-Woverloaded-virtual]
       virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;
                    ^
    executionengine.cpp:186:18: warning:   by ‘virtual void LLVMPYObjectCache::notifyObjectCompiled(const llvm::Module*, int)’ [-Woverloaded-virtual]
         virtual void notifyObjectCompiled(const llvm::Module *M,
                      ^
    executionengine.cpp: In member function ‘virtual void LLVMPYObjectCache::notifyObjectCompiled(const llvm::Module*, int)’:
    executionengine.cpp:191:42: error: request for member ‘getBufferStart’ in ‘MBR’, which is of non-class type ‘int’
                                          MBR.getBufferStart(),
                                              ^
    executionengine.cpp:192:42: error: request for member ‘getBufferSize’ in ‘MBR’, which is of non-class type ‘int’
                                          MBR.getBufferSize() };
                                              ^
    executionengine.cpp: In member function ‘virtual std::unique_ptr<llvm::MemoryBuffer> LLVMPYObjectCache::getObject(const llvm::Module*)’:
    executionengine.cpp:211:21: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<llvm::MemoryBuffer>’ and ‘llvm::MemoryBuffer*’)
                     res = llvm::MemoryBuffer::getMemBufferCopy(
                         ^
    In file included from /usr/include/c++/5.3.0/memory:81:0,
                     from /usr/include/llvm/ADT/SmallVector.h:28,
                     from /usr/include/llvm/IR/DataLayout.h:24,
                     from /usr/include/llvm/IR/Module.h:20,
                     from executionengine.cpp:5:
    /usr/include/c++/5.3.0/bits/unique_ptr.h:249:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = llvm::MemoryBuffer; _Dp = std::default_delete<llvm::MemoryBuffer>]
           operator=(unique_ptr&& __u) noexcept
           ^
    /usr/include/c++/5.3.0/bits/unique_ptr.h:249:7: note:   no known conversion for argument 1 from ‘llvm::MemoryBuffer*’ to ‘std::unique_ptr<llvm::MemoryBuffer>&&’
    /usr/include/c++/5.3.0/bits/unique_ptr.h:269:2: note: candidate: template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::unique_ptr<_Tp, _Dp>::_Pointer::type>, std::__not_<std::is_array<_Up> > >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Up = _Up; _Ep = _Ep; _Tp = llvm::MemoryBuffer; _Dp = std::default_delete<llvm::MemoryBuffer>]
      operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
      ^
    /usr/include/c++/5.3.0/bits/unique_ptr.h:269:2: note:   template argument deduction/substitution failed:
    executionengine.cpp:211:21: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘llvm::MemoryBuffer*’
                     res = llvm::MemoryBuffer::getMemBufferCopy(
                         ^
    In file included from /usr/include/c++/5.3.0/memory:81:0,
                     from /usr/include/llvm/ADT/SmallVector.h:28,
                     from /usr/include/llvm/IR/DataLayout.h:24,
                     from /usr/include/llvm/IR/Module.h:20,
                     from executionengine.cpp:5:
    /usr/include/c++/5.3.0/bits/unique_ptr.h:278:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = llvm::MemoryBuffer; _Dp = std::default_delete<llvm::MemoryBuffer>; std::nullptr_t = std::nullptr_t]
           operator=(nullptr_t) noexcept
           ^
    /usr/include/c++/5.3.0/bits/unique_ptr.h:278:7: note:   no known conversion for argument 1 from ‘llvm::MemoryBuffer*’ to ‘std::nullptr_t’
    executionengine.cpp: In function ‘LLVMPYObjectCache* LLVMPY_CreateObjectCache(ObjectCacheNotifyFunc, ObjectCacheGetObjectFunc, void*)’:
    executionengine.cpp:233:72: error: invalid new-expression of abstract class type ‘LLVMPYObjectCache’
         return new LLVMPYObjectCache(notify_func, getobject_func, user_data);
                                                                            ^
    executionengine.cpp:176:7: note:   because the following virtual functions are pure within ‘LLVMPYObjectCache’:
     class LLVMPYObjectCache : public llvm::ObjectCache {
           ^
    In file included from executionengine.cpp:8:0:
    /usr/include/llvm/ExecutionEngine/ObjectCache.h:30:16: note: 	virtual void llvm::ObjectCache::notifyObjectCompiled(const llvm::Module*, const llvm::MemoryBuffer*)
       virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;
                    ^
    targets.cpp:7:45: fatal error: llvm/Analysis/TargetLibraryInfo.h: No such file or directory
    compilation terminated.
    linker.cpp: In function ‘int LLVMPY_LinkModules(LLVMModuleRef, LLVMModuleRef, int, const char**)’:
    linker.cpp:19:32: error: ‘DiagnosticInfo’ does not name a type
         auto diagnose = [&] (const DiagnosticInfo &DI) {
                                    ^
    linker.cpp:30:6: error: expected ‘)’ before ‘;’ token
         };
          ^
    linker.cpp: In lambda function:
    linker.cpp:30:6: error: expected ‘{’ before ‘;’ token
    linker.cpp: In function ‘int LLVMPY_LinkModules(LLVMModuleRef, LLVMModuleRef, int, const char**)’:
    linker.cpp:32:34: error: ‘LLVMCloneModule’ was not declared in this scope
             Src = LLVMCloneModule(Src);
                                      ^
    linker.cpp:33:74: error: no matching function for call to ‘llvm::Linker::LinkModules(llvm::Module*, llvm::Module*, LLVMPY_LinkModules(LLVMModuleRef, LLVMModuleRef, int, const char**)::<lambda(int)>&)’
         bool failed = Linker::LinkModules(unwrap(Dest), unwrap(Src), diagnose);
                                                                              ^
    In file included from linker.cpp:4:0:
    /usr/include/llvm/Linker/Linker.h:51:17: note: candidate: static bool llvm::Linker::LinkModules(llvm::Module*, llvm::Module*, unsigned int, std::__cxx11::string*)
         static bool LinkModules(Module *Dest, Module *Src, unsigned Mode,
                     ^
    /usr/include/llvm/Linker/Linker.h:51:17: note:   candidate expects 4 arguments, 3 provided
    Makefile.linux:18: recipe for target 'libllvmlite.so' failed
    make: *** [libllvmlite.so] Error 1
    Traceback (most recent call last):
      File "/tmp/pip-build-kp990wi3/llvmlite/ffi/build.py", line 147, in <module>
        main()
      File "/tmp/pip-build-kp990wi3/llvmlite/ffi/build.py", line 137, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-kp990wi3/llvmlite/ffi/build.py", line 129, in main_posix
        subprocess.check_call(['make', '-f', makefile])
      File "/usr/lib/python3.5/subprocess.py", line 584, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
    error: command '/usr/bin/python' failed with exit status 1
```
    
Sorry, I'm not an expert on C++ error messages so I just pasted the whole thing.

Could you please help?

Thank you!

**Comment by pitrou** [comment]
Try compiling from the git master branch. This should be fixed there.

**Comment by pitrou** [comment]
The latest release should now be ok. Please reopen if you still have this issue.
