### ISSUE TITLE
 cannot find -lstdc++

### ISSUE THREAD

**Issue by epifanio** [numba/llvmlite#165]
Hi,

I'm on  a system without root rights, so I'm tring to setup my local environment.
It is a centos 7 linux, I built julia from src which installed llvm as dependency

the llvm files are installed in ```/home/epifanio/dev/julia/usr/lib/```
llvm-config is:

```
which llvm-config 
~/dev/julia/usr/bin/llvm-config
```

```
 llvm-config --cxxflags
-I/home/epifanio/dev/julia/usr/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fPIC -ffunction-sections -fdata-sections -Wcast-qual

llvm-config --ldflags
-L/home/epifanio/dev/julia/usr/lib 

llvm-config --version
3.7.1
```

I'm tring to build ```llvmlite``` but it fails with this error log:

```
python setup.py build
running build
got version from VCS {'version': '0.11.0.dev+6.gc329287', 'full': 'c3292876a5fb404205afee3febec3f3999417339'}
running build_ext
/usr/bin/python /home/epifanio/dev/llvmlite/ffi/build.py
LLVM version... 3.7.1
# static-libstdc++ avoids runtime dependencies on a
# particular libstdc++ version.
g++ -static-libstdc++ -shared -I/home/epifanio/dev/julia/usr/include -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fPIC -ffunction-sections -fdata-sections -Wcast-qual -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -L/home/epifanio/dev/julia/usr/lib -flto -Wl,--exclude-libs=ALL -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMBitWriter -lLLVMIRReader -lLLVMMIRParser -lLLVMAsmParser -lLLVMLibDriver -lLLVMOption -lLLVMDebugInfoPDB -lLLVMTableGen -lLLVMOrcJIT -lLLVMPasses -lLLVMipo -lLLVMVectorize -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMDebugInfoDWARF -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMInstCombine -lLLVMInstrumentation -lLLVMTransformUtils -lLLVMipa -lLLVMMC -lLLVMAnalysis -lLLVMCore -lLLVMSupport -lz -ldl -lm
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [libllvmlite.so] Error 1
Traceback (most recent call last):
  File "/home/epifanio/dev/llvmlite/ffi/build.py", line 141, in <module>
    main()
  File "/home/epifanio/dev/llvmlite/ffi/build.py", line 131, in main
    main_posix('linux', '.so')
  File "/home/epifanio/dev/llvmlite/ffi/build.py", line 123, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
error: command '/usr/bin/python' failed with exit status 1

```

Have you any clue on what I'm missing?

**Comment by ian-bertolacci** [comment]
If I recall correctly, I had to install libstdc++-static on fedora to get it to work.

**Comment by epifanio** [comment]
unfortunately I don't have ```sudo``` rights on this machine.
I just installed gcc from src, using  ```llvm``` installed by ```julia```. 

I installed ```llvmilte``` by:

```pip install -U -e . --user```

It seems to build fine now. I can run ```import llvmlite``` in my python environment.
I'll go ahead and see if I can have ```numba``` installed as well.
Thanks!

**Comment by epifanio** [comment]
no luck, this is what i got trying to install and import ```numba```:

```
[epifanio@jupyter dev]$ cd numba/
[epifanio@jupyter numba]$ pip3 install -U -e . --user
Obtaining file:///home/epifanio/dev/numba
Requirement already up-to-date: llvmlite in /home/epifanio/dev/llvmlite (from numba==0.25.0)
Requirement already up-to-date: numpy in /home/epifanio/.local/lib/python3.4/site-packages (from numba==0.25.0)
Installing collected packages: numba
  Running setup.py develop for numba
Successfully installed numba
You are using pip version 8.0.3, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[epifanio@jupyter numba]$ cd
[epifanio@jupyter ~]$ python3
Python 3.4.3 (default, May  9 2015, 00:06:53) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
Traceback (most recent call last):
  File "/home/epifanio/dev/llvmlite/llvmlite/binding/ffi.py", line 40, in <module>
    lib = ctypes.CDLL(os.path.join(_lib_dir, _lib_name))
  File "/usr/local/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/epifanio/dev/llvmlite/llvmlite/binding/libllvmlite.so: undefined symbol: _ZNKSt14error_category23default_error_conditionEi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/epifanio/dev/numba/numba/__init__.py", line 9, in <module>
    from . import runtests, decorators
  File "/home/epifanio/dev/numba/numba/decorators.py", line 8, in <module>
    from . import config, sigutils
  File "/home/epifanio/dev/numba/numba/config.py", line 10, in <module>
    import llvmlite.binding as ll
  File "/home/epifanio/dev/llvmlite/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/home/epifanio/dev/llvmlite/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/home/epifanio/dev/llvmlite/llvmlite/binding/ffi.py", line 45, in <module>
    lib = ctypes.CDLL(_lib_name)
  File "/usr/local/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libllvmlite.so: cannot open shared object file: No such file or directory
>>> 
```

**Comment by pitrou** [comment]
This is the kind of reason we really recommend using the conda-provided binaries for llvmlite.
You may want to build LLVM yourself but you're on your own. I would also recommend against using two different C++ compilers (one for LLVM, one for llvmlite, apparently...).

**Comment by epifanio** [comment]
@pitrou thanks for the suggestion. I will try to use same gcc, on a debian machine i had no problems in having numba llvmlite and datashader working properly. I'll trat that way first.
