### ISSUE TITLE
LLVM 3.8 support

### ISSUE THREAD

**Issue by humm** [numba/llvmlite#180]
llvmlite does not seem to support llvm38. Even if one remove the check in `ffi/build.py`, then errors ensue:

```
LLVM_CONFIG=/usr/local/Cellar/llvm38/3.8.0/bin/llvm-config-3.8 python setup.py install
/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.12.0.dev+8.g30bcfc0.dirty' to '0.12.0.dev0+8.g30bcfc0.dirty'
  normalized_version,
running install
running build
got version from VCS {'version': '0.12.0.dev+8.g30bcfc0.dirty', 'full': '30bcfc080ac7d36926aa602e6c19593a9149b2fb.dirty'}
running build_ext
/usr/local/bin/python /Users/fabien/research/install/llvmlite/ffi/build.py
LLVM version... 3.8.0

MACOSX_DEPLOYMENT_TARGET=10.7 clang++ -std=c++11 -stdlib=libc++ -dynamiclib -I/usr/local/Cellar/llvm38/3.8.0/lib/llvm-3.8/include -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-common -Wcast-qual -fno-rtti -g assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.dylib -L/usr/local/Cellar/llvm38/3.8.0/lib/llvm-3.8/lib -lLLVMLTO -lLLVMObjCARCOpts -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMMIRParser -lLLVMLibDriver -lLLVMOption -lLLVMTableGen -lLLVMOrcJIT -lLLVMPasses -lLLVMipo -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMDebugInfoCodeView -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMInstrumentation -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMTransformUtils -lLLVMMC -lLLVMBitWriter -lLLVMBitReader -lLLVMAnalysis -lLLVMCore -lLLVMSupport -lz -lpthread -lffi -ledit -lcurses -lm
linker.cpp:20:19: error: member access into incomplete type 'const llvm::DiagnosticInfo'
        switch (DI.getSeverity()) {
                  ^
/usr/local/Cellar/llvm38/3.8.0/lib/llvm-3.8/include/llvm/IR/LLVMContext.h:30:7: note: forward declaration of 'llvm::DiagnosticInfo'
class DiagnosticInfo;
      ^
linker.cpp:29:11: error: member access into incomplete type 'const llvm::DiagnosticInfo'
        DI.print(DP);
          ^
/usr/local/Cellar/llvm38/3.8.0/lib/llvm-3.8/include/llvm/IR/LLVMContext.h:30:7: note: forward declaration of 'llvm::DiagnosticInfo'
class DiagnosticInfo;
      ^
linker.cpp:33:27: error: no member named 'LinkModules' in 'llvm::Linker'
    bool failed = Linker::LinkModules(unwrap(Dest), unwrap(Src), diagnose);
                  ~~~~~~~~^
3 errors generated.
make: *** [all] Error 1
Traceback (most recent call last):
  File "/Users/fabien/research/install/llvmlite/ffi/build.py", line 152, in <module>
    main()
  File "/Users/fabien/research/install/llvmlite/ffi/build.py", line 146, in main
    main_posix('osx', '.dylib')
  File "/Users/fabien/research/install/llvmlite/ffi/build.py", line 134, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.osx']' returned non-zero exit status 2
error: command '/usr/local/bin/python' failed with exit status 1
```

Is support for 3.8 difficult? planned?

**Comment by seibert** [comment]
See #176.  We only support one LLVM minor version (3.7, 3.8, etc) at a time, and usually wait until the .1 release of a new series before switching.  Now that 3.8.1 is out, we should be updating in mid July (after SciPy 2016).

**Comment by humm** [comment]
Thanks for the fast reply! Got it. I'll check it again in mid July.

**Comment by whitequark** [comment]
llvmlite supports 3.8 now.

**Comment by linwoodc3** [comment]
Which version support 3.8.1.  I'm on an isolated system.  HAve llvmlite 12.1 and LLVM 3.8.1 installed.  What version of llvmlite do I need.  Is there any way to add a table in the ReadME with the compatibility information.  Very hard to keep up :-(

**Comment by pitrou** [comment]
@linwoodc3, you need github master right now for LLVM 3.8 support.

The compatibility table is a good idea, submitting a PR is welcome.

**Comment by pitrou** [comment]
Ok, I added a compatibility table in 9963a73d36e95a453d5559c05d7582044442e6d3.
