### ISSUE TITLE
Getting RuntimeError even when I have llvm-3.8 installed

### ISSUE THREAD

**Issue by konsbn** [numba/llvmlite#220]
I have llvm installed as is evident by
```
export LLVM_CONFIG="/usr/bin/llvm-config"
```
 and also the ls output
```
➜  llvmlite git:(master) ls /usr/bin/llvm-
llvm-ar@              llvm-cov@             llvm-dwarfdump@       llvm-mc@              llvm-prof@            llvm-size-3.6@      
llvm-ar-3.4@          llvm-cov-3.4@         llvm-dwarfdump-3.4@   llvm-mc-3.4@          llvm-profdata-3.6@    llvm-size-3.8@      
llvm-ar-3.6@          llvm-cov-3.6@         llvm-dwarfdump-3.6@   llvm-mc-3.6@          llvm-profdata-3.8@    llvm-split-3.8@     
llvm-ar-3.8@          llvm-cov-3.8@         llvm-dwarfdump-3.8@   llvm-mc-3.8@          llvm-ranlib@          llvm-stress-3.4@    
llvm-as@              llvm-c-test-3.8@      llvm-dwp-3.8@         llvm-mcmarkup-3.4@    llvm-ranlib-3.4@      llvm-stress-3.6@    
llvm-as-3.4@          llvm-cxxdump-3.8@     llvm-extract@         llvm-mcmarkup-3.6@    llvm-ranlib-3.6@      llvm-stress-3.8@    
llvm-as-3.6@          llvm-diff@            llvm-extract-3.4@     llvm-mcmarkup-3.8@    llvm-ranlib-3.8@      llvm-symbolizer-3.4@
llvm-as-3.8@          llvm-diff-3.4@        llvm-extract-3.6@     llvm-nm@              llvm-readobj-3.4@     llvm-symbolizer-3.6@
llvm-bcanalyzer@      llvm-diff-3.6@        llvm-extract-3.8@     llvm-nm-3.4@          llvm-readobj-3.6@     llvm-symbolizer-3.8@
llvm-bcanalyzer-3.4@  llvm-diff-3.8@        llvm-ld@              llvm-nm-3.6@          llvm-readobj-3.8@     llvm-tblgen@        
llvm-bcanalyzer-3.6@  llvm-dis@             llvm-lib-3.8@         llvm-nm-3.8@          llvm-rtdyld@          llvm-tblgen-3.4@    
llvm-bcanalyzer-3.8@  llvm-dis-3.4@         llvm-link@            llvm-objdump@         llvm-rtdyld-3.4@      llvm-tblgen-3.6@    
llvm-config@          llvm-dis-3.6@         llvm-link-3.4@        llvm-objdump-3.4@     llvm-rtdyld-3.6@      llvm-tblgen-3.8@    
llvm-config-3.4@      llvm-dis-3.8@         llvm-link-3.6@        llvm-objdump-3.6@     llvm-rtdyld-3.8@      llvm-vtabledump-3.6@
llvm-config-3.6@      llvm-dsymutil-3.6@    llvm-link-3.8@        llvm-objdump-3.8@     llvm-size@                                
llvm-config-3.8@      llvm-dsymutil-3.8@    llvm-lto-3.8@         llvm-pdbdump-3.8@     llvm-size-3.4@                            


```
but I keep getting 
```
➜  llvmlite git:(master) sudo python setup.py build
running build
got version from VCS {'version': '0.14.0+8.gc996fb6', 'full': 'c996fb6ada525a53e7659477f57a825d6d1b8632'}
running build_ext
/usr/bin/python /home/sbn/llvmlite/ffi/build.py
LLVM version... 3.4

Traceback (most recent call last):
  File "/home/sbn/llvmlite/ffi/build.py", line 152, in <module>
    main()
  File "/home/sbn/llvmlite/ffi/build.py", line 142, in main
    main_posix('linux', '.so')
  File "/home/sbn/llvmlite/ffi/build.py", line 119, in main_posix
    raise RuntimeError(msg)
RuntimeError: Building llvmlite requires LLVM 3.8.x. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

error: command '/usr/bin/python' failed with exit status 1
```
# Please HELP ME!

**Comment by seibert** [comment]
It looks like you have LLVM 3.4, 3.6, and 3.8 installed.  I'm not sure which version `llvm-config` is pointing at, but maybe it will work if you try this:
```
export LLVM_CONFIG="/usr/bin/llvm-config-3.8"
```

**Comment by konsbn** [comment]
Tried it already didn't work

**Comment by stuartarchibald** [comment]
Are you using `sudo` to build? Is the env var set for the super user?

**Comment by konsbn** [comment]
Yep I did that I did sudo -E su and then set environment variable didn't work

**Comment by pitrou** [comment]
So you did the following:
```
$ sudo -E su
$ export LLVM_CONFIG="/usr/bin/llvm-config-3.8"
$ python setup.py build
```
and you still got the error above?

**Comment by aditi73** [comment]
hao

**Comment by seibert** [comment]
Closing issue, as this is out of date now.
