### ISSUE TITLE
/usr/local/include/llvm/Support/type_traits.h:17:10: fatal error: 'type_traits'       file not found #include <type_traits>

### ISSUE THREAD

**Issue by sc-lj** [numba/llvmlite#257]
In file included from assembly.cpp:1:
In file included from /usr/local/include/llvm/IR/LLVMContext.h:18:
In file included from /usr/local/include/llvm/Support/CBindingWrapping.h:17:
In file included from /usr/local/include/llvm/Support/Casting.h:19:
/usr/local/include/llvm/Support/type_traits.h:17:10: fatal error: 'type_traits'
      file not found
#include <type_traits>
         ^
1 error generated.
make: *** [all] Error 1
Traceback (most recent call last):
  File "/Users/lj/Downloads/llvmlite-llvmdev3.9.1/ffi/build.py", line 152, in <module>
    main()
  File "/Users/lj/Downloads/llvmlite-llvmdev3.9.1/ffi/build.py", line 146, in main
    main_posix('osx', '.dylib')
  File "/Users/lj/Downloads/llvmlite-llvmdev3.9.1/ffi/build.py", line 134, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.osx']' returned non-zero exit status 2
error: command '/usr/bin/python' failed with exit status 1

how can i fix it?

**Comment by sc-lj** [comment]
my computer is macos 10.12

**Comment by sklam** [comment]
Which branch/commit are you on?
The master branch requires llvm4.0.
