### ISSUE TITLE
Can't install llvmlite 0.18.0 on Windows

### ISSUE THREAD

**Issue by GTmAster** [numba/llvmlite#266]
Can't install llvmlite via pip on Windows.
OS Windows 10 64bit
CMake 3.8.1
pip 9.0.1

pip install llvmlite:
```
Collecting llvmlite
  Using cached llvmlite-0.18.0.tar.gz
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite: started
  Running setup.py bdist_wheel for llvmlite: finished with status 'error'
  Complete output from command "C:\Program Files\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\PAA\\AppData\\Local\\Temp\\pip-build-fuio7ioc\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\PAA\AppData\Local\Temp\tmpjmr3gxicpip-wheel- --python-tag cp36:
  running bdist_wheel
  C:\Program Files\Anaconda3\python.exe C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py
  -- The C compiler identification is MSVC 19.0.24218.2
  -- The CXX compiler identification is MSVC 19.0.24218.2
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/PAA/AppData/Local/Temp/tmpho3pmbpe
  -- The C compiler identification is MSVC 19.0.24218.2
  -- The CXX compiler identification is MSVC 19.0.24218.2
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:7 (find_package):
    Could not find a package configuration file provided by "LLVM" with any of
    the following names:
  
      LLVMConfig.cmake
      llvm-config.cmake
  
    Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
    "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
    provides a separate development package or SDK, be sure it has been
    installed.
  
  
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/PAA/AppData/Local/Temp/pip-build-fuio7ioc/llvmlite/ffi/build/CMakeFiles/CMakeOutput.log".
  Trying generator 'Visual Studio 14 2015 Win64'
  Traceback (most recent call last):
    File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 141, in <module>
      main()
    File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 129, in main
      main_win32()
    File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 79, in main_win32
      try_cmake(here_dir, build_dir, generator)
    File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 27, in try_cmake
      subprocess.check_call(['cmake', '-G', generator, cmake_dir])
    File "C:\Program Files\Anaconda3\lib\subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-G', 'Visual Studio 14 2015 Win64', 'C:\\Users\\PAA\\AppData\\Local\\Temp\\pip-build-fuio7ioc\\llvmlite\\ffi']' returned non-zero exit status 1.
  error: command 'C:\\Program Files\\Anaconda3\\python.exe' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
  Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    Complete output from command "C:\Program Files\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\PAA\\AppData\\Local\\Temp\\pip-build-fuio7ioc\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PAA\AppData\Local\Temp\pip-ypmk2tje-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\llvmlite/_version.py {'version': '0.18.0', 'full': '5282a37619286624edbef830e1eda38b5c9469f6'}
    running build_ext
    C:\Program Files\Anaconda3\python.exe C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py
    -- The C compiler identification is MSVC 19.0.24218.2
    -- The CXX compiler identification is MSVC 19.0.24218.2
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/PAA/AppData/Local/Temp/tmpqqu6s_qk
    CMake Error at CMakeLists.txt:7 (find_package):
      Could not find a package configuration file provided by "LLVM" with any of
      the following names:
    
        LLVMConfig.cmake
        llvm-config.cmake
    
      Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
      "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/PAA/AppData/Local/Temp/pip-build-fuio7ioc/llvmlite/ffi/build/CMakeFiles/CMakeOutput.log".
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 141, in <module>
        main()
      File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 129, in main
        main_win32()
      File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 79, in main_win32
        try_cmake(here_dir, build_dir, generator)
      File "C:\Users\PAA\AppData\Local\Temp\pip-build-fuio7ioc\llvmlite\ffi\build.py", line 27, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Program Files\Anaconda3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '-G', 'Visual Studio 14 2015 Win64', 'C:\\Users\\PAA\\AppData\\Local\\Temp\\pip-build-fuio7ioc\\llvmlite\\ffi']' returned non-zero exit status 1.
    error: command 'C:\\Program Files\\Anaconda3\\python.exe' failed with exit status 1
    
    ----------------------------------------

```

**Comment by sklam** [comment]
We don't have wheels for llvmlite on windows yet.  Your best option is to use [conda](https://conda.io/miniconda.html) to get prebuilt packages.

**Comment by newgre** [comment]
Any update on this? Is there a plan on making this work or even an ETA?

**Comment by seibert** [comment]
ETA for Numba/llvmlite wheels for all platforms is the next Numba release at the end of August.

**Comment by ethanhs** [comment]
It seems pypi has wheels for all platforms.

**Comment by esc** [comment]
> It seems pypi has wheels for all platforms.

Indeed and has done for the last 4 years. I'll close this one now as it's long completed.
