### ISSUE TITLE
KeyError: '.const.pickledata...'

### ISSUE THREAD

**Issue by cgohlke** [numba/llvmlite#285]
Using the just released numba 0.34.0, llvmlite 0.19.0, LLVM 4.0.1, built with Visual Studio 2015 on Windows, I get the following failure on all Python platforms:
```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba, llvmlite
>>> numba.__version__
'0.33.0'
>>> llvmlite.__version__
'0.19.0'
>>> @numba.jit()
... def function():
...     pass
...
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\numba\pythonapi.py", line 1297, in serialize_object
    gv = self.module.__serialized[obj]
KeyError: (<class 'RuntimeError'>, ('numba jitted function aborted due to unresolved symbol',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "X:\Python36\lib\site-packages\numba\decorators.py", line 173, in wrapper
    **dispatcher_args)
  File "X:\Python36\lib\site-packages\numba\dispatcher.py", line 467, in __init__
    self.targetctx = self.targetdescr.target_context
  File "X:\Python36\lib\site-packages\numba\targets\registry.py", line 54, in target_context
    return self._toplevel_target_context
  File "X:\Python36\lib\site-packages\numba\utils.py", line 283, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "X:\Python36\lib\site-packages\numba\targets\registry.py", line 38, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "X:\Python36\lib\site-packages\numba\targets\base.py", line 240, in __init__
    self.init()
  File "X:\Python36\lib\site-packages\numba\targets\cpu.py", line 48, in init
    rtsys.initialize(self)
  File "X:\Python36\lib\site-packages\numba\runtime\nrt.py", line 35, in initialize
    self._library = nrtdynmod.compile_nrt_functions(ctx)
  File "X:\Python36\lib\site-packages\numba\runtime\nrtdynmod.py", line 199, in compile_nrt_functions
    ir_mod, library = create_nrt_module(ctx)
  File "X:\Python36\lib\site-packages\numba\runtime\nrtdynmod.py", line 189, in create_nrt_module
    _define_nrt_unresolved_abort(ctx, ir_mod)
  File "X:\Python36\lib\site-packages\numba\runtime\nrtdynmod.py", line 166, in _define_nrt_unresolved_abort
    ctx.call_conv.return_user_exc(builder, RuntimeError, (msg,))
  File "X:\Python36\lib\site-packages\numba\targets\callconv.py", line 344, in return_user_exc
    struct_gv = pyapi.serialize_object(exc)
  File "X:\Python36\lib\site-packages\numba\pythonapi.py", line 1299, in serialize_object
    struct = self.serialize_uncached(obj)
  File "X:\Python36\lib\site-packages\numba\pythonapi.py", line 1282, in serialize_uncached
    arr = self.context.insert_unique_const(self.module, name, bdata)
  File "X:\Python36\lib\site-packages\numba\targets\base.py", line 401, in insert_unique_const
    gv = mod.get_global(name)
  File "X:\Python36\lib\site-packages\llvmlite\ir\module.py", line 138, in get_global
    return self.globals[name]
KeyError: '.const.pickledata.2066756346184'
```

**Comment by cgohlke** [comment]
For some reason pip did not upgrade to numba 0.34. Everything's working now. Sorry for the noise.
