### ISSUE TITLE
Make wheels for windows

### ISSUE THREAD

**Issue by sklam** [numba/llvmlite#290]
Currently, `python setup.py bdist_wheel` is failing with:

```
Traceback (most recent call last):
  File "setup.py", line 182, in <module>
    ext_modules=[ext_stub] if not sys.platform.startswith('win32') else [],
  File "C:\conda64_2\envs\llvmlite_wheel_tmp35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\conda64_2\envs\llvmlite_wheel_tmp35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\conda64_2\envs\llvmlite_wheel_tmp35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 125, in run
    raise RuntimeError("missing {}".format(path))
RuntimeError: missing llvmlite\binding\msvcr120.dll
```

**Comment by ethanhs** [comment]
I think this can be closed :)

**Comment by seibert** [comment]
Oh right, thanks!
