### ISSUE TITLE
Possible LLVM IR Parsing Error

### ISSUE THREAD

**Issue by abarbaro** [numba/llvmlite#331]
Hi all,
I know that I have opened a similar issue a while ago but following the previous suggestions I cannot figure out if I'm missing something.

I have compiled pngpixel with the following command ```clang -S -emit-llvm pngpixel.c``` and used the ```pngpixel.ll``` with the following script:

```
import llvmlite

print(llvmlite.__version__)

import llvmlite.binding as llvm
llvm.initialize()

with open('pngpixel.ll') as f:
    data = f.read()

llvm.parse_assembly(data)
```

Unfortunately the output was:

```
➜  /tmp python test.py 
0.22.0
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    llvm.parse_assembly(data)
  File "/home/al/anaconda3/lib/python3.6/site-packages/llvmlite/binding/module.py", line 22, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: LLVM IR parsing error
<string>:67:18: error: expected comma after load's type
  %4 = load i32* %2, align 4
```

Any idea on how to fix it please?

Thanks

**Comment by abarbaro** [comment]
I have an old version of LLVM..

Sorry
