### ISSUE TITLE
llvm 6.0.0 linking issue on macOS

### ISSUE THREAD

**Issue by defjaf** [numba/llvmlite#346]
Link error on MacOS -- related to `_LLVMInitializeInstCombine`.  I think this is really [a problem with llvmlite 6.0.0](https://reviews.llvm.org/D44140), but I wonder if it's possible to fix "downstream"?

See below for output from an attempted install.

```
$ MACOSX_DEPLOYMENT_TARGET=10.13 LLVM_CONFIG=/usr/local/Cellar/llvm/6.0.0/bin/llvm-config CC=clang CXX=clang++ pip3 install --upgrade llvmlite
Collecting llvmlite
  Using cached https://files.pythonhosted.org/packages/c6/0f/d33ec3d030d4de01ba251c7dcf1051cb9f558221d64421439a61b0d81020/llvmlite-0.23.0.tar.gz
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/nc/n7d98d0x46g0h5yyb4bc1gv40000gv/T/pip-install-sc7dfuli/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/nc/n7d98d0x46g0h5yyb4bc1gv40000gv/T/pip-wheel-7y1_8n14 --python-tag cp36:
  running bdist_wheel
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /private/var/folders/nc/n7d98d0x46g0h5yyb4bc1gv40000gv/T/pip-install-sc7dfuli/llvmlite/ffi/build.py
  LLVM version... MACOSX_DEPLOYMENT_TARGET=10.13 clang++ -std=c++11 -stdlib=libc++ -dynamiclib -I/usr/local/Cellar/llvm/6.0.0/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -DNDEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp object_file.cpp -o libllvmlite.dylib -L/usr/local/Cellar/llvm/6.0.0/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMMIRParser -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMCoverage -lLLVMTableGen -lLLVMDlltoolDriver -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiAsmPrinter -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMARMUtils -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMWindowsManifest -lLLVMFuzzMutate -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle -lz -lcurses -lm
  Undefined symbols for architecture x86_64:
    "_LLVMInitializeInstCombine", referenced from:
        _LLVMPY_InitializeInstCombine in initfini-84d84a.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [all] Error 1
  6.0.0
  
  Traceback (most recent call last):
    File "/private/var/folders/nc/n7d98d0x46g0h5yyb4bc1gv40000gv/T/pip-install-sc7dfuli/llvmlite/ffi/build.py", line 143, in <module>
      main()
    File "/private/var/folders/nc/n7d98d0x46g0h5yyb4bc1gv40000gv/T/pip-install-sc7dfuli/llvmlite/ffi/build.py", line 137, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/nc/n7d98d0x46g0h5yyb4bc1gv40000gv/T/pip-install-sc7dfuli/llvmlite/ffi/build.py", line 125, in main_posix
      subprocess.check_call(['make', '-f', makefile])
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.osx']' returned non-zero exit status 2.
  error: command '/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6' failed with exit status 1
  ```

**Comment by stuartarchibald** [comment]
Thanks for the report, this is already patched in the LLVM conda builds using this patch https://github.com/numba/llvmlite/blob/master/conda-recipes/0001-Transforms-Add-missing-header-for-InstructionCombini.patch applied here https://github.com/numba/llvmlite/blob/master/conda-recipes/llvmdev/meta.yaml#L19-L20. If you are using your own LLVM then I think you'll have to patch it manually and rebuild?

**Comment by defjaf** [comment]
I've been using homebrew llvm; I don't know how to add a patch to that!

For my purposes, I think all I need are official wheels on pypi.org, which I would install instead of compiling from source.

**Comment by stuartarchibald** [comment]
Ah ok, see https://github.com/numba/numba/issues/2918#issuecomment-384142644.

**Comment by sklam** [comment]
All the wheels are uploaded to PyPI now.
