### ISSUE TITLE
llvmlite 0.22.0 "FileNotFoundError: [Errno 2] No such file or directory: 'make': 'make'" on Alpine Linux (Docker)

### ISSUE THREAD

**Issue by m3talstorm** [numba/llvmlite#377]
Relevant DockerFile:

```
FROM python:3.7.0b5-alpine3.7

RUN apk add --no-cache --virtual .build-deps \
    gcc=6.4.0-r5 \
    musl-dev=1.1.18-r3 \
    python3-dev=3.6.3-r9 \
    libffi-dev=3.2.1-r4 \
    llvm=5.0.0-r0 \
    llvm-dev=5.0.0-r0 \
    # Postgres
    libpq=10.4-r0 \
    postgresql-dev=10.4-r0 \
    py-psycopg2=2.7.3.2-r0 \
    postgresql=10.4-r0 \
    # Other
    git=2.15.2-r0

RUN pip install --no-cache-dir -r requirements.txt
```

Relevant requirements.txt:

```
llvmlite==0.22.0
numba==0.37.0
numpy==1.14.5
```

Output of pip install inside Docker build:

```
  Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r22yyklu/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ye9xs_vj/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-r22yyklu/llvmlite/llvmlite/_version.py {'version': '0.22.0', 'full': '46b4b5e288f3a175332ad68d8c3745c63fbb5701'}
    running build_ext
    /usr/local/bin/python /tmp/pip-install-r22yyklu/llvmlite/ffi/build.py
    LLVM version... 5.0.0

    Traceback (most recent call last):
      File "/tmp/pip-install-r22yyklu/llvmlite/ffi/build.py", line 141, in <module>
        main()
      File "/tmp/pip-install-r22yyklu/llvmlite/ffi/build.py", line 131, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-r22yyklu/llvmlite/ffi/build.py", line 123, in main_posix
        subprocess.check_call(['make', '-f', makefile])
      File "/usr/local/lib/python3.7/subprocess.py", line 323, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/usr/local/lib/python3.7/subprocess.py", line 304, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/local/lib/python3.7/subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.7/subprocess.py", line 1499, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'make': 'make'
    error: command '/usr/local/bin/python' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r22yyklu/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ye9xs_vj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-r22yyklu/llvmlite/
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

```

**Comment by seibert** [comment]
We do not have Python 3.7 wheels posted yet, so pip is trying to build from source, which you can't do on a minimal Linux distribution.  We are updating our build system and should have Python 3.7 wheels next week.

**Comment by m3talstorm** [comment]
I made it less minimal by adding ALL THE THINGS from https://github.com/gliderlabs/docker-alpine/issues/24#issuecomment-89770836

```
    gcc=6.4.0-r5 \
    musl-dev=1.1.18-r3 \
```

with:

```
alpine-sdk \
```

 :)

And it seems to compile, ill use this in the mean time, till the 3.7 wheel is out.

**Comment by seibert** [comment]
Python 3.7 wheels are up now.

**Comment by Odianosen25** [comment]
I have this same issue please @seibert, using python 3.8.5. Any luck?

**Comment by esc** [comment]
@Odianosen25 thanks for adding to this issue. Since the issue is quite old and also references older versions of Numba and llvmlite I would suggest opening a new issue with the relevant details regarding the issue you are facing. Thank you!
