### ISSUE TITLE
[Manually Install llvmlite] OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by zhangysh1995** [numba/llvmlite#416]
I followed the [Docs](https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html) to build, (using **vagrant** for VM and **Conda** for virtual environment)
````
(devp) vagrant@ubuntu-xenial:~$ export LLVM_CONFIG=/home/vagrant/anaconda3/envs/devp/bin/llvm-config
(devp) vagrant@ubuntu-xenial:~$ cd llvmlite/; python setup.py build
/home/vagrant/anaconda3/envs/devp/lib/python2.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '0.26.0dev0+51.g5be6c73' to '0.26.0.dev0+51.g5be6c73'
  normalized_version,
running build
got version from VCS {'version': '0.26.0dev0+51.g5be6c73', 'full': '5be6c7315869345fa0c98253441512343aeec47e'}
running build_ext
/home/vagrant/anaconda3/envs/devp/bin/python /home/vagrant/llvmlite/ffi/build.py
LLVM version... 6.0.0

SVML detected
Traceback (most recent call last):
  File "/home/vagrant/llvmlite/ffi/build.py", line 167, in <module>
    main()
  File "/home/vagrant/llvmlite/ffi/build.py", line 157, in main
    main_posix('linux', '.so')
  File "/home/vagrant/llvmlite/ffi/build.py", line 149, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/home/vagrant/anaconda3/envs/devp/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/vagrant/anaconda3/envs/devp/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/vagrant/anaconda3/envs/devp/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/vagrant/anaconda3/envs/devp/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
error: command '/home/vagrant/anaconda3/envs/devp/bin/python' failed with exit status 1
````
The doc says:

> If your LLVM is installed in a nonstandard location, set the LLVM_CONFIG environment variable to the location of the corresponding llvm-config or llvm-config.exe executable. This variable must persist into the installation of llvmlite—for example, into a Python environment.
> 
> EXAMPLE: If LLVM is installed in /opt/llvm/ with the llvm-config binary located at /opt/llvm/bin/llvm-config, set LLVM_CONFIG=/opt/llvm/bin/llvm-config.

But my `llvm-config` path is correct:
````
(devp) vagrant@ubuntu-xenial:~/llvmlite$ /home/vagrant/anaconda3/envs/devp/bin/llvm-config
usage: llvm-config <OPTION>... [<COMPONENT>...]

Get various configuration information needed to compile programs which use
LLVM.  Typically called from 'configure' scripts.  Examples:
  llvm-config --cxxflags
  llvm-config --ldflags
  llvm-config --libs engine bcreader scalaropts

Options:
  --version         Print LLVM version.
````

My packages:
````
llvmdev             6.0.0              hf484d3e_4    numba (in Conda)
llvmlite            commit 5be6c7      master
````
I will go into the code and find the problem, but could anyone help me with this?

**Comment by zhangysh1995** [comment]
This is caused because my vagrant machine doesn't have `make`. Closed.
