### ISSUE TITLE
KeyError is not defined in binding/ffi

### ISSUE THREAD

**Issue by dnelson86** [numba/llvmlite#418]
I've run into:

```python
Exception ignored in: <bound method ObjectRef.__del__ of <llvmlite.binding.executionengine.ExecutionEngine object at 0x7f96d11cfd30>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 243, in __del__
  File "/usr/local/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 204, in close
  File "/usr/local/lib/python3.6/site-packages/llvmlite/binding/executionengine.py", line 205, in _dispose
  File "/usr/local/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 52, in __getattr__
NameError: name 'KeyError' is not defined
```

with cffi 1.11.5, llvmlite 0.25.0, numba 0.40.1, python 3.6.7. Am I missing something obvious here?

**Comment by dnelson86** [comment]
To follow up and close, not really an issue in llvmlite I believe.

Similar to https://stackoverflow.com/questions/44939556/nameerror-name-hasattr-is-not-defined-python3-6-django1-11-ubuntu16-17-a

related to being embedded inside an apache process which terminates the python interpreter.
