### ISSUE TITLE
Guide on migrating from llvmpy

### ISSUE THREAD

**Issue by martmists** [numba/llvmlite#432]
I'm considering reworking an old project of mine, but I couldn't find any docs on migrating. Where would I start looking for how to do so?

**Comment by seibert** [comment]
We don't have any documentation, but llvmlite still has an `llvmpy` submodule which provides some backward compatible interfaces that were used to ease the Numba transition several years ago:

https://github.com/numba/llvmlite/tree/master/llvmlite/llvmpy

You might find them helpful to quickly update your code, as well as examples of how old APIs map to the new APIs.

**Comment by seibert** [comment]
(Note that the llvmpy -> llvmlite transition was several years ago, so these backward compatibility interfaces may be removed in a future release.)

**Comment by martmists** [comment]
It seems a lot was changed sadly, starting off with this: 
```
Traceback (most recent call last):
  File "/home/mart/git/pyjit/core.py", line 10, in <module>
    from constants import function_cache, module
  File "/home/mart/git/pyjit/constants.py", line 2, in <module>
    from llvmlite.llvmpy.ee import TargetMachine, EngineBuilder
ModuleNotFoundError: No module named 'llvmlite.llvmpy.ee'
```

**Comment by martmists** [comment]
Additionally, llvmpy.Module.new no longer exists. It seems a lot of llvmpy internals were changed, making this transition very difficult.
