### ISSUE TITLE
Build problem with llvm 3.6

### ISSUE THREAD

**Issue by rainwoodman** [numba/llvmlite#46]
I guess 3.6 is not supported anyways, but would file this FYI.

Thanks

```
yfeng1@edison07:~/source/llvmlite> python setup.py build
running build
got version from VCS {'version': '0.2.2-1-gbcb15be', 'full': 'bcb15bee8c28e4f4e65a8d4c636af9d97f8d1e8c'}
running build_ext
/usr/common/usg/python/2.7.5/bin/python ffi/build.py
LLVM version... 3.6.0svn
# static-libstdc++ avoids runtime dependencies on a
# particular libstdc++ version.
g++ -static-libstdc++ -shared -flto `llvm-config --cxxflags` -fno-rtti assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -flto `llvm-config --ldflags` -Wl,--exclude-libs=ALL `llvm-config --system-libs --libs all`
assembly.cpp: In function 'LLVMOpaqueModule* LLVMPY_ParseAssembly(LLVMContextRef, const char*, const char**)':
assembly.cpp:25:70: error: 'ParseAssemblyString' was not declared in this scope
     Module *m = ParseAssemblyString(ir, NULL, error, *unwrap(context));
                                                                      ^
executionengine.cpp: In function 'void LLVMPY_LinkInJIT()':
executionengine.cpp:11:19: error: 'LLVMLinkInJIT' was not declared in this scope
     LLVMLinkInJIT();
                   ^
executionengine.cpp: In function 'LLVMOpaqueExecutionEngine* create_execution_engine(LLVMModuleRef, LLVMTargetMachineRef, char**, bool)':
executionengine.cpp:70:43: error: no matching function for call to 'llvm::EngineBuilder::EngineBuilder(llvm::Module*)'
     llvm::EngineBuilder eb(llvm::unwrap(M));
                                           ^
executionengine.cpp:70:43: note: candidate is:
In file included from executionengine.cpp:4:0:
/global/common/edison/graphics/llvm/3.6/static/include/llvm/ExecutionEngine/ExecutionEngine.h:510:3: note: llvm::EngineBuilder::EngineBuilder(std::unique_ptr<llvm::Module>)
   EngineBuilder(std::unique_ptr<Module> M);
   ^
/global/common/edison/graphics/llvm/3.6/static/include/llvm/ExecutionEngine/ExecutionEngine.h:510:3: note:   no known conversion for argument 1 from 'llvm::Module*' to 'std::unique_ptr<llvm::Module>'
executionengine.cpp:74:8: error: 'class llvm::EngineBuilder' has no member named 'setUseMCJIT'
     eb.setUseMCJIT(useMCJIT);
        ^
linker.cpp: In function 'int LLVMPY_LinkModules(LLVMModuleRef, LLVMModuleRef, unsigned int, const char**)':
linker.cpp:14:51: error: no matching function for call to 'llvm::Linker::LinkModules(llvm::Module*, llvm::Module*, unsigned int&, std::string*)'
                                       &errorstring);
                                                   ^
linker.cpp:14:51: note: candidates are:
In file included from linker.cpp:3:0:
/global/common/edison/graphics/llvm/3.6/static/include/llvm/Linker/Linker.h:77:15: note: static bool llvm::Linker::LinkModules(llvm::Module*, llvm::Module*, llvm::Linker::DiagnosticHandlerFunction)
   static bool LinkModules(Module *Dest, Module *Src,
               ^
/global/common/edison/graphics/llvm/3.6/static/include/llvm/Linker/Linker.h:77:15: note:   candidate expects 3 arguments, 4 provided
/global/common/edison/graphics/llvm/3.6/static/include/llvm/Linker/Linker.h:80:15: note: static bool llvm::Linker::LinkModules(llvm::Module*, llvm::Module*)
   static bool LinkModules(Module *Dest, Module *Src);
               ^
/global/common/edison/graphics/llvm/3.6/static/include/llvm/Linker/Linker.h:80:15: note:   candidate expects 2 arguments, 4 provided
make: *** [libllvmlite.so] Error 1
Traceback (most recent call last):
  File "ffi/build.py", line 112, in <module>
    main()
  File "ffi/build.py", line 104, in main
    main_posix('linux', '.so')
  File "ffi/build.py", line 96, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/usr/common/usg/python/2.7.5/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
error: command '/usr/common/usg/python/2.7.5/bin/python' failed with exit status 1

```

**Comment by rainwoodman** [comment]
my bad. saw the 3.6 branch
