### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by brettgilio** [numba/llvmlite#537]
Hi there. I am a project committer and member of https://guix.gnu.org/.

We use llvmlite for the packaging of Numba in our repository. We are facing an interesting issue that I am trying to determine if it is coming from upstream or if it is an issue on our end. Hopefully you might be able to help us out. The issue is a single failure during the test sequence with the output

`AttributeError: 'NoneType' object has no attribute 'encode'`

Here is the full backtrace and partial log.

```
running install_egg_info
running egg_info
creating llvmlite.egg-info
writing llvmlite.egg-info/PKG-INFO
writing dependency_links to llvmlite.egg-info/dependency_links.txt
writing requirements to llvmlite.egg-info/requires.txt
writing top-level names to llvmlite.egg-info/top_level.txt
writing manifest file 'llvmlite.egg-info/SOURCES.txt'
reading manifest file 'llvmlite.egg-info/SOURCES.txt'
writing manifest file 'llvmlite.egg-info/SOURCES.txt'
Copying llvmlite.egg-info to /gnu/store/dcjpgmy1kvkshpr6c4md647shqikkd50-python-llvmlite-0.30.0/lib/python3.7/site-packages/llvmlite-0.30.0-py3.7.egg-info
running install_scripts
phase `install' succeeded after 0.3 seconds
starting phase `wrap'
find-files: /gnu/store/dcjpgmy1kvkshpr6c4md647shqikkd50-python-llvmlite-0.30.0/bin: No such file or directory
find-files: /gnu/store/dcjpgmy1kvkshpr6c4md647shqikkd50-python-llvmlite-0.30.0/sbin: No such file or directory
phase `wrap' succeeded after 0.0 seconds
starting phase `check'
running "python setup.py" with command "test" and parameters ()
running test
running egg_info
writing llvmlite.egg-info/PKG-INFO
writing dependency_links to llvmlite.egg-info/dependency_links.txt
writing requirements to llvmlite.egg-info/requires.txt
writing top-level names to llvmlite.egg-info/top_level.txt
reading manifest file 'llvmlite.egg-info/SOURCES.txt'
writing manifest file 'llvmlite.egg-info/SOURCES.txt'
running build_ext
/gnu/store/l8nphg0idd8pfddyad8f92lx8d1hc053-python-wrapper-3.7.4/bin/python /tmp/guix-build-python-llvmlite-0.30.0.drv-0/llvmlite-0.30.0/ffi/build.py
LLVM version... make: Nothing to be done for 'all'.
7.0.1

SVML detected
..s.E.........................................................s....................................................................................................................................................................s..........................
======================================================================
ERROR: test_libm (llvmlite.tests.test_binding.TestDylib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-llvmlite-0.30.0.drv-0/llvmlite-0.30.0/llvmlite/tests/test_binding.py", line 1270, in test_libm
    llvm.load_library_permanently(libm)
  File "/tmp/guix-build-python-llvmlite-0.30.0.drv-0/llvmlite-0.30.0/llvmlite/binding/dylib.py", line 29, in load_library_permanently
    _encode_string(filename), outerr):
  File "/tmp/guix-build-python-llvmlite-0.30.0.drv-0/llvmlite-0.30.0/llvmlite/binding/common.py", line 17, in _encode_string
    encoded = s.encode('latin1')
AttributeError: 'NoneType' object has no attribute 'encode'

----------------------------------------------------------------------
Ran 254 tests in 1.618s

FAILED (errors=1, skipped=3)
command "python" "-c" "import setuptools, tokenize;__file__='setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))" "test" failed with status 1
builder for `/gnu/store/fxbjak8fxmskxj15siwc3aw87xqk1mkj-python-llvmlite-0.30.0.drv' failed with exit code 1
build of /gnu/store/fxbjak8fxmskxj15siwc3aw87xqk1mkj-python-llvmlite-0.30.0.drv failed
View build log at '/var/log/guix/drvs/fx/bjak8fxmskxj15siwc3aw87xqk1mkj-python-llvmlite-0.30.0.drv.bz2'.
cannot build derivation `/gnu/store/8idyvwrx7ymwbjnzk58s9g6k18nfws16-python-bbknn-1.3.6.drv': 1 dependencies couldn't be built
guix build: error: build of `/gnu/store/8idyvwrx7ymwbjnzk58s9g6k18nfws16-python-bbknn-1.3.6.drv' failed
```

What do you think?

**Comment by sklam** [comment]
The error came from the test's unexpected failure to find the `libm.so`. The test is doing a `ctypes.find_library('m')` but it's returning `None`. I'm not familiar with guix. Is there a `libm` that we can load dynamically?

**Comment by Apteryks** [comment]
Hello, and thank you for looking into this!  The problem is Guix-specific.  `ctypes.util.find_library` looks up a shared library like so:

```
        def find_library(name):
            # See issue #9998
            return _findSoname_ldconfig(name) or \
                   _get_soname(_findLib_gcc(name) or _findLib_ld(name))
```

The above depends on the presence of `gcc` in the PATH, which actually is the case here so _findLib_gcc(name) returns '/gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libm.so', but then the result gets ruined by `_get_soname`, which does

```
        def _get_soname(f):
            # assuming GNU binutils / ELF
            if not f:
                return None
            objdump = shutil.which('objdump')
            if not objdump:
                # objdump is not available, give up
                return None

            try:
                proc = subprocess.Popen((objdump, '-p', '-j', '.dynamic', f),
                                        stdout=subprocess.PIPE,
                                        stderr=subprocess.DEVNULL)
            except OSError:  # E.g. bad executable
                return None
            with proc:
                dump = proc.stdout.read()
            res = re.search(br'\sSONAME\s+([^\s]+)', dump)
            if not res:
                return None
            return os.fsdecode(res.group(1))
```
e.g., it depends on `objdump` in PATH else returns None. `objdump` is currently missing in the build environment of llvmlite in Guix.

And even when objdump is present, it eventually tries to dlopen the .so and fails, because the .so is wrapped in a ld script:

```
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libm.so.6  AS_NEEDED ( /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libmvec.so.1 ) )
```

The typical workaround in Guix is to refer to the shared libraries by their absolute path, which suites the functional model well and doesn't require setting LD_LIBRARY_PATH or suffer from the above problem.

This issue can now be closed, thank you!

Maxim
