### ISSUE TITLE
Better error message when cmake is missing

### ISSUE THREAD

**Issue by ARF1** [numba/llvmlite#566]
The manual specifies that `cmake` is required to build `llvmlite`. 

That said, the error message that is shown if it happens to be missing could be made clearer:

```
Trying generator 'Visual Studio 14 2015 Win64'
Traceback (most recent call last):
  File "Z:\llvmlite\ffi\build.py", line 168, in <module>
    main()
  File "Z:\llvmlite\ffi\build.py", line 156, in main
    main_win32()
  File "Z:\llvmlite\ffi\build.py", line 89, in main_win32
    generator = find_win32_generator()
  File "Z:\llvmlite\ffi\build.py", line 77, in find_win32_generator
    try_cmake(cmake_dir, build_dir, generator)
  File "Z:\llvmlite\ffi\build.py", line 28, in try_cmake
    subprocess.check_call(['cmake', '-G', generator, cmake_dir])
  File "Z:\Systemdateien\Miniconda3\envs\stm32\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "Z:\Systemdateien\Miniconda3\envs\stm32\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "Z:\Systemdateien\Miniconda3\envs\stm32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "Z:\Systemdateien\Miniconda3\envs\stm32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
error: command 'Z:\\Systemdateien\\Miniconda3\\envs\\stm32\\python.exe' failed with exit status 1
```

**Comment by esc** [comment]
@ARF1 thanks for submitting this, I have labeled it as a feature request.
