### ISSUE TITLE
Importing numba crashes the program when importing llvmlite-0.32.0

### ISSUE THREAD

**Issue by antoniohps** [numba/llvmlite#579]
The expression:

`import numba`

causes a program crash with:

- Python 2.7
- numba 0.47.0
- llvmlite 0.32.0

Changing numba version does not seem to work.
Downgrading to llvmlite-0.31.0 fixes it.

Error stack:

```
Traceback (most recent call last):
  File "/home/robotics/catkin_ws/src/my_navigation/scripts/teste_numba.py", line 1, in <module>
    import numba
  File "/usr/local/lib/python2.7/dist-packages/numba/__init__.py", line 196, in <module>
    import numba.typed
  File "/usr/local/lib/python2.7/dist-packages/numba/typed/__init__.py", line 3, in <module>
    from .typeddict import Dict
  File "/usr/local/lib/python2.7/dist-packages/numba/typed/typeddict.py", line 19, in <module>
    @njit
  File "/usr/local/lib/python2.7/dist-packages/numba/decorators.py", line 238, in njit
    return jit(*args, **kws)
  File "/usr/local/lib/python2.7/dist-packages/numba/decorators.py", line 175, in jit
    return wrapper(pyfunc)
  File "/usr/local/lib/python2.7/dist-packages/numba/decorators.py", line 191, in wrapper
    **dispatcher_args)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 650, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/usr/local/lib/python2.7/dist-packages/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/usr/local/lib/python2.7/dist-packages/numba/utils.py", line 390, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/usr/local/lib/python2.7/dist-packages/numba/targets/base.py", line 260, in __init__
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/targets/cpu.py", line 61, in init
    rtsys.initialize(self)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/runtime/nrt.py", line 39, in initialize
    self._library = nrtdynmod.compile_nrt_functions(ctx)
  File "/usr/local/lib/python2.7/dist-packages/numba/runtime/nrtdynmod.py", line 210, in compile_nrt_functions
    library.add_ir_module(ir_mod)
  File "/usr/local/lib/python2.7/dist-packages/numba/targets/codegen.py", line 200, in add_ir_module
    ir = cgutils.normalize_ir_text(str(ir_module))
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/module.py", line 244, in __repr__
    lines += self._get_metadata_lines()
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/module.py", line 222, in _get_metadata_lines
    mdbuf.append(str(md))
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/_utils.py", line 48, in __str__
    s = self.__cached_str = self._to_string()
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/values.py", line 223, in _to_string
    self.descr(buf)
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/values.py", line 354, in descr
    operands.append(op.get_reference())
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/_utils.py", line 58, in get_reference
    s = self.__cached_refstr = self._get_reference()
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/values.py", line 277, in _get_reference
    return '!"{0}"'.format(_escape_string(self.string))
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/ir/values.py", line 36, in _escape_string
    buf = [_map[ch] for ch in text]
KeyError: 'b'
```

**Comment by esc** [comment]
@antoniohps thanks for asking about this. I believe you may have a version mismatch. The combo Numba 0.47.0 and llvmlite 0.31.0 is the last combination to work with Python 2.7. Could you upgrade your Python perhaps and see if that helps to run more recent versions?

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
