### ISSUE TITLE
Install of umap-learn, numba or fastparquet seems broken since 0.32.0

### ISSUE THREAD

**Issue by finalspy** [numba/llvmlite#584]
I have several Dockerfile files, installing a bunch of python libraries through pip. 
Since llvmlite 0.32.0 release I noticed that install of :

- numba

- umap-learn 

- fastparquet

are broken with the following errors : 

```ERROR: Command errored out with exit status 1:
 command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ss534tpz/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ss534tpz/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ogzwqmk9
     cwd: /tmp/pip-install-ss534tpz/llvmlite/
Complete output (26 lines):
running bdist_wheel
/usr/local/bin/python /tmp/pip-install-ss534tpz/llvmlite/ffi/build.py
LLVM version... Traceback (most recent call last):
  File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 106, in main_posix
    out = subprocess.check_output([llvm_config, '--version'])
  File "/usr/local/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 168, in <module>
    main()
  File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 158, in main
    main_posix('linux', '.so')
  File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 109, in main_posix
    "to the path for llvm-config" % (llvm_config,))
RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
error: command '/usr/local/bin/python' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for llvmlite
```

and also

```ERROR: Command errored out with exit status 1:
  command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ss534tpz/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ss534tpz/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h5s50idg/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5m/llvmlite
      cwd: /tmp/pip-install-ss534tpz/llvmlite/
 Complete output (29 lines):
 running install
 running build
 got version from file /tmp/pip-install-ss534tpz/llvmlite/llvmlite/_version.py {'full': '26059d238f4ba23dff74703dd27168591d889edd', 'version': '0.32.0'}
 running build_ext
 /usr/local/bin/python /tmp/pip-install-ss534tpz/llvmlite/ffi/build.py
 LLVM version... Traceback (most recent call last):
   File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 106, in main_posix
     out = subprocess.check_output([llvm_config, '--version'])
   File "/usr/local/lib/python3.5/subprocess.py", line 316, in check_output
     **kwargs).stdout
   File "/usr/local/lib/python3.5/subprocess.py", line 383, in run
     with Popen(*popenargs, **kwargs) as process:
   File "/usr/local/lib/python3.5/subprocess.py", line 676, in __init__
     restore_signals, start_new_session)
   File "/usr/local/lib/python3.5/subprocess.py", line 1289, in _execute_child
     raise child_exception_type(errno_num, err_msg)
 FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 168, in <module>
     main()
   File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 158, in main
     main_posix('linux', '.so')
   File "/tmp/pip-install-ss534tpz/llvmlite/ffi/build.py", line 109, in main_posix
     "to the path for llvm-config" % (llvm_config,))
 RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
 error: command '/usr/local/bin/python' failed with exit status 1
 ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ss534tpz/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ss534tpz/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h5s50idg/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5m/llvmlite Check the logs for full command output.
```

This occurs with python 3.5, 3.6 or 3.7 (didn't try other versions). 
My Dockerfiles are based on `python:3.x-slim-buster`

Downgrading to llvmlite to 0.31.0 by explicitely adding before other installs via `pip install llvmlite==0.31.0` fixes the problems.

**Comment by seibert** [comment]
This looks like pip is not finding the manylinux1 wheels we posted for version 0.32.0, and so is trying to build llvmlite from source (which requires a full LLVM build which you obviously won't have in your docker image).  Following NumPy's lead with [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), we've stopped building packages for Python 3.5 and earlier beginning with 0.32.0, but you should have been successful with Python 3.6 and up.

@sklam: Was there a window of time where the sdist was posted before the wheels?

**Comment by finalspy** [comment]
OK i double checked it again and the errors I had with Python 3.6 and 3.7 aren't linked to llvmlite. 
So I guess for python 3.5 this is due to end of support on python 3.5 as you mentioned.
So you can close this.

**Comment by finalspy** [comment]
After reviewing all the Python 3.7 logs I noticed this warning : 
```
...
Collecting llvmlite<=0.33.0.dev0,>=0.31.0.dev0
  Downloading llvmlite-0.32.0-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 328, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 39, in response_chunks
    decode_content=False,
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
Collecting numba<0.48,>=0.47
  Downloading numba-0.47.0-cp37-cp37m-manylinux1_x86_64.whl (3.7 MB)
Collecting llvmlite>=0.31.0dev0
  Downloading llvmlite-0.32.0-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
...
```
But anyway the installs seems ok in the end...

**Comment by stuartarchibald** [comment]
Thanks for reporting back @finalspy, looks like this is resolved. Closing.
