### ISSUE TITLE
Failing to build llvmlite

### ISSUE THREAD

**Issue by Namburger** [numba/llvmlite#588]
Hi guys, this maybe a very minor issues because the gist is that I cannot find my static libs for building llvmlite. It started with me trying to build `librosa` which all finished. But when I try running it, I encounter [this error](https://github.com/librosa/librosa/issues/1116). Their team suggested that I try compiling llvmlite or ping you guys for help. I tried to compile it my self first but encountered this:
```
$ LLVM_CONFIG=/usr/lib/llvm-7/bin/llvm-config python3 setup.py build
/usr/lib/python3/dist-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.33.0dev0+17.gc4f5a08' to '0.33.0.dev0+17.gc4f5a08'
  normalized_version,
running build
got version from VCS {'version': '0.33.0dev0+17.gc4f5a08', 'full': 'c4f5a085c9f9c7a192579b02a11347bfc2ac768b'}
running build_ext
/usr/bin/python3 /home/mendel/sdcard/llvmlite/ffi/build.py
LLVM version... 7.0.1

Traceback (most recent call last):
  File "/home/mendel/sdcard/llvmlite/ffi/build.py", line 192, in <module>
    main()
  File "/home/mendel/sdcard/llvmlite/ffi/build.py", line 182, in main
    main_posix('linux', '.so')
  File "/home/mendel/sdcard/llvmlite/ffi/build.py", line 147, in main_posix
    libs = run_llvm_config(llvm_config, "--system-libs --libs all".split())
  File "/home/mendel/sdcard/llvmlite/ffi/build.py", line 44, in run_llvm_config
    % (cmd, rc, err))
RuntimeError: Command ['/usr/lib/llvm-7/bin/llvm-config', '--system-libs', '--libs', 'all'] returned with code 1; stderr follows:
llvm-config: error: component libraries and shared library

llvm-config: error: missing: /usr/lib/llvm-7/lib/libLLVMDemangle.a
llvm-config: error: missing: /usr/lib/llvm-7/lib/libLLVMSupport.a
llvm-config: error: missing: /usr/lib/llvm-7/lib/libLLVMBinaryFormat.a
llvm-config: error: missing: /usr/lib/llvm-7/lib/libLLVMCore.a
llvm-config: error: missing: /usr/lib/llvm-7/lib/libLLVMBitReader.a
.......
```
For reference:
```
/home/mendel/sdcard/llvmlite$ dpkg -l | grep llvm
ii  libllvm7:arm64                       1:7.0.1-8                           arm64        Modular compiler and toolchain technologies, runtime library
ii  llvm                                 1:7.0-47                            arm64        Low-Level Virtual Machine (LLVM)
ii  llvm-7                               1:7.0.1-8                           arm64        Modular compiler and toolchain technologies
ii  llvm-7-runtime                       1:7.0.1-8                           arm64        Modular compiler and toolchain technologies, IR interpreter
ii  llvm-runtime                         1:7.0-47                            arm64        Low-Level Virtual Machine (LLVM), bytecode interpreter
ii  python3-llvmlite                     0.27.0-2                            arm64        LLVM Python 3 binding for writing JIT compilers
```

It seems that the error is either missing dynamic libs or static libs even though package installation are usually okay :P

**Comment by stuartarchibald** [comment]
Thanks for the report. The `build.py` script in the above is just running the command:
```
/usr/lib/llvm-7/bin/llvm-config --system-libs --libs all
```
that it is failing suggests that there's some part of the `LLVM` toolchain missing on your system (that which provides the static libraries). From https://packages.ubuntu.com/eoan/arm64/llvm-7-dev/filelist I suspect you need to install the `llvm-7-dev` package.

**Comment by Namburger** [comment]
@stuartarchibald NICE!
I guess the real issue is my googling skills :p
