### ISSUE TITLE
llvmlite landingpad throw RuntimeError:LandingPadInst needs to be in a function with a personality?

### ISSUE THREAD

**Issue by QY77** [numba/llvmlite#600]
I use llvmlite to translate `try ... except ...`, when I use function `landingpad`, it can generate IR, but throw an error when verifying it, I already search docs about this, I find it was moved(https://github.com/numba/llvmlite/pull/156), I can't solve it, help...

demo code:
```
    try:
        e = a * b
        f = 2 / 3
        print(e)
    except Exception as e:
        # pass
        print(e)
```
source code:
```
    def translate_except(self, builder_except):

        tp_pers = ir.FunctionType(ir.IntType(8), (), var_arg=True)
        pers = ir.Function(self.module, tp_pers, '__gxx_personality_v0')

        landingpad = builder_except.landingpad(ir.LiteralStructType([ir.IntType(32), ir.IntType(8).as_pointer()]),
                                    'lp')
        int_typeinfo = ir.GlobalVariable(builder_except.function.module, ir.IntType(8).as_pointer(),
                                         "_ZTIi")
        int_typeinfo.global_constant = True
        int_typeinfo.linkage = 'internal'
        int_typeinfo.unnamed_addr = True
        landingpad.add_clause(ir.CatchClause(int_typeinfo))
        landingpad.add_clause(ir.FilterClause(ir.Constant(ir.ArrayType(int_typeinfo.type, 1),
                                                  [int_typeinfo])))

        return landingpad

...
...
...
# vevify
mod = llvm.parse_assembly(str(handle_bc.module))
            mod.verify()
            print('verify Done.')

```
gen IR:
```
...
...
except.11233:
  %"lp" = landingpad {i32, i8*}
      catch i8** @"_ZTIi"
      filter [1 x i8**] [i8** @"_ZTIi"]
  %"11244" = load i32, i32* %"e.4", align 8
  call void (...) @"print"(i32 %"11244")
  resume {i32, i8*} %"lp"
...
...
```
verify it still throw this, :
```
Traceback (most recent call last):
  File "D:/python/bc2ir/BC_TO_IR.py", line 317, in main
    mod.verify()
  File "C:\Python\lib\site-packages\llvmlite\binding\module.py", line 115, in verify
    raise RuntimeError(str(outmsg))
RuntimeError: LandingPadInst needs to be in a function with a personality.
  %lp = landingpad { i32, i8* }
          catch i8** @_ZTIi
          filter [1 x i8**] [i8** @_ZTIi]
Instruction does not dominate all uses!
  %e.4 = alloca i32, i32 8
  %"11244" = load i32, i32* %e.4, align 8
ResumeInst needs to be in a function with a personality.
  resume { i32, i8* } %lp
```

**Comment by sklam** [comment]
It's missing `builder.function.attributes.personality = pers`. The personality needs to be set to the function. Have a look at the corresponding test for the change https://github.com/numba/llvmlite/pull/156/files#diff-f27716e681986d8996eab3d7f05cb6ea

**Comment by QY77** [comment]
thanks, bro, I add attr, and I solve it.
