### ISSUE TITLE
llvmlite build error

### ISSUE THREAD

**Issue by robomotic** [numba/llvmlite#645]
Hi folks,
I have seen this error in a previous issue but it appears to be back.
My setup:
pip 20.2.4 with  (python 3.7)
OS:
Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

Error:
pip3 install numba

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numba
  Using cached https://www.piwheels.org/simple/numba/numba-0.51.2-cp37-cp37m-linux_armv7l.whl (2.9 MB)
Requirement already satisfied: setuptools in /home/pi/.virtualenvs/pynomad/lib/python3.7/site-packages (from numba) (50.3.0)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
Requirement already satisfied: numpy>=1.15 in /home/pi/.virtualenvs/pynomad/lib/python3.7/site-packages (from numba) (1.19.2)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/.virtualenvs/pynomad/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bc9u598b/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bc9u598b/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qexfrb22
       cwd: /tmp/pip-install-bc9u598b/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /home/pi/.virtualenvs/pynomad/bin/python3.7 /tmp/pip-install-bc9u598b/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/home/pi/.virtualenvs/pynomad/bin/python3.7' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/pi/.virtualenvs/pynomad/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bc9u598b/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bc9u598b/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7pvel_8i/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.virtualenvs/pynomad/include/site/python3.7/llvmlite
         cwd: /tmp/pip-install-bc9u598b/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-bc9u598b/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /home/pi/.virtualenvs/pynomad/bin/python3.7 /tmp/pip-install-bc9u598b/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-bc9u598b/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/home/pi/.virtualenvs/pynomad/bin/python3.7' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/.virtualenvs/pynomad/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bc9u598b/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bc9u598b/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7pvel_8i/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.virtualenvs/pynomad/include/site/python3.7/llvmlite Check the logs for full command output.
```

**Comment by esc** [comment]
@robomotic thanks for asking about this. It seems like you are attempting to install a pre-compiled wheel on an RaspberrryPi running a 32 bit OS. However, we don't currently ship wheels for this platform. The only two viable ways to install the Numba stack on a RaspberryPi right now are to `conda` and 'compile it yourself'. The only documentation we currently have on this is at: https://numba.pydata.org/numba-doc/latest/user/installing.html#installing-on-linux-armv7-platforms

**Comment by robomotic** [comment]
Thanks I followed that and worked like a charm!

**Comment by esc** [comment]
@robomotic thanks for reporting back, glad it worked for you! Enjoy Numba!
