### ISSUE TITLE
LLVM won't build on Pi 400 despite specification of LLVM_CONFIG as advised

### ISSUE THREAD

**Issue by readyready15728** [numba/llvmlite#714]
```
pi@raspberrypi:~/src/llvmlite $ LLVM_CONFIG=/usr/bin/llvm-config-9 sudo -H pip3 install llvmlite
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting llvmlite
  Using cached https://files.pythonhosted.org/packages/19/66/6b2c49c7c68da48d17059882fdb9ad9ac9e5ac3f22b00874d7996e3c44a8/llvmlite-0.36.0.tar.gz
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rorfhrma/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-diilg33m --python-tag cp37:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-rorfhrma/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-rorfhrma/llvmlite/ffi/build.py", line 220, in <module>
      main()
    File "/tmp/pip-install-rorfhrma/llvmlite/ffi/build.py", line 210, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-rorfhrma/llvmlite/ffi/build.py", line 134, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/usr/bin/python3' failed with exit status 1

  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rorfhrma/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-k4dqi8q7/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-rorfhrma/llvmlite/llvmlite/_version.py {'version': '0.36.0', 'full': 'e6bb8d137d922bec8beeb01a237254778759becd'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-rorfhrma/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-rorfhrma/llvmlite/ffi/build.py", line 220, in <module>
        main()
      File "/tmp/pip-install-rorfhrma/llvmlite/ffi/build.py", line 210, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-rorfhrma/llvmlite/ffi/build.py", line 134, in main_posix
        raise RuntimeError(msg) from None
    RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-rorfhrma/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-k4dqi8q7/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-rorfhrma/llvmlite/
```

Running `LLVM_CONFIG=/usr/bin/llvm-config-9 sudo python3 setup.py install` manually has similar results.

Output of `lsb_release -a`:

```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by esc** [comment]
@readyready15728 thank you for submitting this to the llvmlite issue tracker.  Allow me to ask a few questions. Where did you get the `llvm-config-9`. Is this something you compiled manually or did you install this using the operating systems package management facilities? Also, how is your `sudo` configured to handle environment variables? For example, what does `LLVM_CONFIG=/usr/bin/llvm-config-9 sudo echo $LLVM_CONFIG` yield?

**Comment by readyready15728** [comment]
> @readyready15728 thank you for submitting this to the llvmlite issue tracker. Allow me to ask a few questions. Where did you get the `llvm-config-9`. Is this something you compiled manually or did you install this using the operating systems package management facilities? Also, how is your `sudo` configured to handle environment variables? For example, what does `LLVM_CONFIG=/usr/bin/llvm-config-9 sudo echo $LLVM_CONFIG` yield?

It's an official package. `LLVM_CONFIG=/usr/bin/llvm-config-9 sudo echo $LLVM_CONFIG` was blank. What helped was doing `sudo bash` then `python3 setup.py install`; it succeeded. Presumably pip would respond the same.

**Comment by esc** [comment]
> It's an official package. `LLVM_CONFIG=/usr/bin/llvm-config-9 sudo echo $LLVM_CONFIG` was blank. What helped was doing `sudo bash` then `python3 setup.py install`; it succeeded. Presumably pip would respond the same.

OK, yes, that makes sense then. Probably `env_reset` is set in your `sudoers` file , which means that `LLVM_CONFIG` does not "survive" past the "sudo" call.  The workarounds are indeed to use `sudo bash` and then set the `LLVM_CONFIG` inside the root shell or to re-configure `sudo` using `sudo visudo` to `env_keep` the correct environment variables. 

In any case, I am glad you managed to solve it and thank you for using llvmlite!
