### ISSUE TITLE
libLLVMSupport.a (Commandline.cpp.obj): fatal error LNK1143: invalid or currupt file

### ISSUE THREAD

**Issue by ahmed-taj** [numba/llvmlite#74]
Hi, 
I always get this error while trying to build llvmlite v0.6.0.dev  using llvm 3.6.1 in Windows 8.1 with python 3.4.3 (32 bit) 

```
E:\llvmlite-0.6.0.dev>python setup.py install
C:\Python34\lib\site-packages\setuptools\dist.py:283: UserWarning: The version specified requires normalization, consider using '0.6.0.dev0' instead of '0.6.0.dev'.
  self.metadata.version,
running install
running build
got version from expanded keyword {'full': '0daf5c67c380a7ab3126e0ac0575b413d0f5e58a', 'version': '0.6.0.dev'}
running build_ext
C:\Python34\python.exe ffi\build.py
Trying generator 'Visual Studio 12 2013'
-- The C compiler identification is MSVC 18.0.31101.0
-- The CXX compiler identification is MSVC 18.0.31101.0
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013
-- Check for working CXX compiler using: Visual Studio 12 2013 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/One/AppData/Local/Temp/tmphme6mk52
-- Found LLVM 3.6.1
-- Using LLVMConfig.cmake in: C:/LLVM/share/llvm/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: E:/llvmlite-0.6.0.dev/ffi/build
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.34003]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/19/2015 12:15:13 PM.
Project "E:\llvmlite-0.6.0.dev\ffi\build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "E:\llvmlite-0.6.0.dev\ffi\build\ALL_BUILD.vcxproj" (1) is building "E:\llvmlite-0.6.0.dev\ffi\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
InitializeBuildStatus:
  Creating "Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
FinalizeBuildStatus:
  Deleting file "Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "E:\llvmlite-0.6.0.dev\ffi\build\ZERO_CHECK.vcxproj" (default targets).

Project "E:\llvmlite-0.6.0.dev\ffi\build\ALL_BUILD.vcxproj" (1) is building "E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj" (3) on node 1 (default targets).
InitializeBuildStatus:
  Touching "llvmlite.dir\Release\llvmlite.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /IC:\LLVM\include /nologo /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D __STDC_LIMIT_MACROS /D __STDC_CONSTANT_MACROS
   /D "CMAKE_INTDIR=\"Release\"" /D llvmlite_EXPORTS /D _WINDLL /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"llvmlite.dir\Release\\" /Fd"llvmlite.dir\Release\vc120.pdb" /G
  d /TP /analyze- /errorReport:queue "E:\llvmlite-0.6.0.dev\ffi\assembly.cpp" "E:\llvmlite-0.6.0.dev\ffi\bitcode.cpp" "E:\llvmlite-0.6.0.dev\ffi\core.cpp" "E:\llvmlite-0.6.0.dev\ffi\dylib.cpp" "E:\ll
  vmlite-0.6.0.dev\ffi\executionengine.cpp" "E:\llvmlite-0.6.0.dev\ffi\initfini.cpp" "E:\llvmlite-0.6.0.dev\ffi\linker.cpp" "E:\llvmlite-0.6.0.dev\ffi\module.cpp" "E:\llvmlite-0.6.0.dev\ffi\passmanag
  ers.cpp" "E:\llvmlite-0.6.0.dev\ffi\targets.cpp" "E:\llvmlite-0.6.0.dev\ffi\transforms.cpp" "E:\llvmlite-0.6.0.dev\ffi\value.cpp"
  assembly.cpp
C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throws
an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
      C:\LLVM\include\llvm/IR/Metadata.h(596) : see declaration of 'llvm::MDNode::operator new'
  bitcode.cpp
  core.cpp
E:\llvmlite-0.6.0.dev\ffi\core.cpp(8): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details. [E:\llvmlit
e-0.6.0.dev\ffi\build\llvmlite.vcxproj]
      C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\string.h(245) : see declaration of 'strdup'
  dylib.cpp
E:\llvmlite-0.6.0.dev\ffi\dylib.cpp(27): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details. [E:\llvml
ite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
      C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\string.h(245) : see declaration of 'strdup'
  executionengine.cpp
C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throws
an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
      C:\LLVM\include\llvm/IR/Metadata.h(596) : see declaration of 'llvm::MDNode::operator new'
E:\llvmlite-0.6.0.dev\ffi\executionengine.cpp(74): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details.
 [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
      C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\string.h(245) : see declaration of 'strdup'
C:\LLVM\include\llvm/ADT/IntrusiveRefCntPtr.h(180): warning C4800: 'llvm::sys::fs::detail::DirIterState *const ' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev
\ffi\build\llvmlite.vcxproj]
      C:\LLVM\include\llvm/ADT/IntrusiveRefCntPtr.h(180) : while compiling class template member function 'llvm::IntrusiveRefCntPtr<llvm::sys::fs::detail::DirIterState>::operator bool(void) const
  '
      C:\LLVM\include\llvm/Support/FileSystem.h(762) : see reference to function template instantiation 'llvm::IntrusiveRefCntPtr<llvm::sys::fs::detail::DirIterState>::operator bool(void) const'
  being compiled
      C:\LLVM\include\llvm/Support/FileSystem.h(732) : see reference to class template instantiation 'llvm::IntrusiveRefCntPtr<llvm::sys::fs::detail::DirIterState>' being compiled
  initfini.cpp
  linker.cpp
C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throws
an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
      C:\LLVM\include\llvm/IR/Metadata.h(596) : see declaration of 'llvm::MDNode::operator new'
  module.cpp
C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throws
an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
      C:\LLVM\include\llvm/IR/Metadata.h(596) : see declaration of 'llvm::MDNode::operator new'
  passmanagers.cpp
  targets.cpp
C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  transforms.cpp
E:\llvmlite-0.6.0.dev\ffi\transforms.cpp(117): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
E:\llvmlite-0.6.0.dev\ffi\transforms.cpp(133): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  value.cpp
  Generating Code...
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"E:\llvmlite-0.6.0.dev\ffi\build\Release\llvmlite.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gd
  i32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib C:\LLVM\lib\libLLVMSupport.a C:\LLVM\lib\libLLVMTableGen.a C:\LLVM\lib\libLLVMCore.a C:\LLVM\lib\libLLVMIR
  Reader.a C:\LLVM\lib\libLLVMCodeGen.a C:\LLVM\lib\libLLVMSelectionDAG.a C:\LLVM\lib\libLLVMAsmPrinter.a C:\LLVM\lib\libLLVMBitReader.a C:\LLVM\lib\libLLVMBitWriter.a C:\LLVM\lib\libLLVMTransformUti
  ls.a C:\LLVM\lib\libLLVMInstrumentation.a C:\LLVM\lib\libLLVMInstCombine.a C:\LLVM\lib\libLLVMScalarOpts.a C:\LLVM\lib\libLLVMipo.a C:\LLVM\lib\libLLVMVectorize.a C:\LLVM\lib\libLLVMObjCARCOpts.a C
  :\LLVM\lib\libLLVMLinker.a C:\LLVM\lib\libLLVMAnalysis.a C:\LLVM\lib\libLLVMipa.a C:\LLVM\lib\libLLVMLTO.a C:\LLVM\lib\libLLVMMC.a C:\LLVM\lib\libLLVMMCParser.a C:\LLVM\lib\libLLVMMCDisassembler.a
  C:\LLVM\lib\libLLVMObject.a C:\LLVM\lib\libLLVMOption.a C:\LLVM\lib\libLLVMDebugInfo.a C:\LLVM\lib\libLLVMExecutionEngine.a C:\LLVM\lib\libLLVMInterpreter.a C:\LLVM\lib\libLLVMMCJIT.a C:\LLVM\lib\l
  ibLLVMRuntimeDyld.a C:\LLVM\lib\libLLVMTarget.a C:\LLVM\lib\libLLVMAArch64CodeGen.a C:\LLVM\lib\libLLVMAArch64Info.a C:\LLVM\lib\libLLVMAArch64AsmParser.a C:\LLVM\lib\libLLVMAArch64Disassembler.a C
  :\LLVM\lib\libLLVMAArch64AsmPrinter.a C:\LLVM\lib\libLLVMAArch64Desc.a C:\LLVM\lib\libLLVMAArch64Utils.a C:\LLVM\lib\libLLVMARMCodeGen.a C:\LLVM\lib\libLLVMARMInfo.a C:\LLVM\lib\libLLVMARMAsmParser
  .a C:\LLVM\lib\libLLVMARMDisassembler.a C:\LLVM\lib\libLLVMARMAsmPrinter.a C:\LLVM\lib\libLLVMARMDesc.a C:\LLVM\lib\libLLVMCppBackendCodeGen.a C:\LLVM\lib\libLLVMCppBackendInfo.a C:\LLVM\lib\libLLV
  MHexagonCodeGen.a C:\LLVM\lib\libLLVMHexagonInfo.a C:\LLVM\lib\libLLVMHexagonDesc.a C:\LLVM\lib\libLLVMHexagonDisassembler.a C:\LLVM\lib\libLLVMMipsCodeGen.a C:\LLVM\lib\libLLVMMipsAsmPrinter.a C:\
  LLVM\lib\libLLVMMipsDisassembler.a C:\LLVM\lib\libLLVMMipsInfo.a C:\LLVM\lib\libLLVMMipsDesc.a C:\LLVM\lib\libLLVMMipsAsmParser.a C:\LLVM\lib\libLLVMMSP430CodeGen.a C:\LLVM\lib\libLLVMMSP430AsmPrin
  ter.a C:\LLVM\lib\libLLVMMSP430Info.a C:\LLVM\lib\libLLVMMSP430Desc.a C:\LLVM\lib\libLLVMNVPTXCodeGen.a C:\LLVM\lib\libLLVMNVPTXInfo.a C:\LLVM\lib\libLLVMNVPTXAsmPrinter.a C:\LLVM\lib\libLLVMNVPTXD
  esc.a C:\LLVM\lib\libLLVMPowerPCCodeGen.a C:\LLVM\lib\libLLVMPowerPCAsmParser.a C:\LLVM\lib\libLLVMPowerPCDisassembler.a C:\LLVM\lib\libLLVMPowerPCAsmPrinter.a C:\LLVM\lib\libLLVMPowerPCInfo.a C:\L
  LVM\lib\libLLVMPowerPCDesc.a C:\LLVM\lib\libLLVMR600CodeGen.a C:\LLVM\lib\libLLVMR600AsmParser.a C:\LLVM\lib\libLLVMR600AsmPrinter.a C:\LLVM\lib\libLLVMR600Info.a C:\LLVM\lib\libLLVMR600Desc.a C:\L
  LVM\lib\libLLVMSparcCodeGen.a C:\LLVM\lib\libLLVMSparcInfo.a C:\LLVM\lib\libLLVMSparcDesc.a C:\LLVM\lib\libLLVMSparcAsmPrinter.a C:\LLVM\lib\libLLVMSparcAsmParser.a C:\LLVM\lib\libLLVMSparcDisassem
  bler.a C:\LLVM\lib\libLLVMSystemZCodeGen.a C:\LLVM\lib\libLLVMSystemZAsmParser.a C:\LLVM\lib\libLLVMSystemZDisassembler.a C:\LLVM\lib\libLLVMSystemZAsmPrinter.a C:\LLVM\lib\libLLVMSystemZInfo.a C:\
  LLVM\lib\libLLVMSystemZDesc.a C:\LLVM\lib\libLLVMX86CodeGen.a C:\LLVM\lib\libLLVMX86AsmParser.a C:\LLVM\lib\libLLVMX86Disassembler.a C:\LLVM\lib\libLLVMX86AsmPrinter.a C:\LLVM\lib\libLLVMX86Desc.a
  C:\LLVM\lib\libLLVMX86Info.a C:\LLVM\lib\libLLVMX86Utils.a C:\LLVM\lib\libLLVMXCoreCodeGen.a C:\LLVM\lib\libLLVMXCoreDisassembler.a C:\LLVM\lib\libLLVMXCoreAsmPrinter.a C:\LLVM\lib\libLLVMXCoreInfo
  .a C:\LLVM\lib\libLLVMXCoreDesc.a C:\LLVM\lib\libLLVMAsmParser.a C:\LLVM\lib\libLLVMLineEditor.a C:\LLVM\lib\libLLVMProfileData.a C:\LLVM\lib\libgtest.a C:\LLVM\lib\libgtest_main.a C:\LLVM\lib\libL
  TO.dll.a C:\LLVM\lib\libLLVMBitWriter.a C:\LLVM\lib\libLLVMObjCARCOpts.a C:\LLVM\lib\libLLVMLinker.a C:\LLVM\lib\libLLVMExecutionEngine.a C:\LLVM\lib\libLLVMRuntimeDyld.a C:\LLVM\lib\libLLVMAArch64
  AsmPrinter.a C:\LLVM\lib\libLLVMAArch64Info.a C:\LLVM\lib\libLLVMAArch64Utils.a C:\LLVM\lib\libLLVMARMInfo.a C:\LLVM\lib\libLLVMARMAsmPrinter.a C:\LLVM\lib\libLLVMHexagonDesc.a C:\LLVM\lib\libLLVMH
  exagonInfo.a C:\LLVM\lib\libLLVMMipsDesc.a C:\LLVM\lib\libLLVMMipsAsmPrinter.a C:\LLVM\lib\libLLVMMipsInfo.a C:\LLVM\lib\libLLVMMSP430AsmPrinter.a C:\LLVM\lib\libLLVMMSP430Info.a C:\LLVM\lib\libLLV
  MNVPTXInfo.a C:\LLVM\lib\libLLVMNVPTXAsmPrinter.a C:\LLVM\lib\libLLVMPowerPCAsmPrinter.a C:\LLVM\lib\libLLVMPowerPCInfo.a C:\LLVM\lib\libLLVMipo.a C:\LLVM\lib\libLLVMVectorize.a C:\LLVM\lib\libLLVM
  R600AsmPrinter.a C:\LLVM\lib\libLLVMR600Info.a C:\LLVM\lib\libLLVMSparcDesc.a C:\LLVM\lib\libLLVMSparcAsmPrinter.a C:\LLVM\lib\libLLVMSparcInfo.a C:\LLVM\lib\libLLVMSystemZAsmPrinter.a C:\LLVM\lib\
  libLLVMSystemZInfo.a C:\LLVM\lib\libLLVMX86CodeGen.a C:\LLVM\lib\libLLVMX86Desc.a C:\LLVM\lib\libLLVMX86AsmPrinter.a C:\LLVM\lib\libLLVMX86Utils.a C:\LLVM\lib\libLLVMX86Info.a C:\LLVM\lib\libLLVMSe
  lectionDAG.a C:\LLVM\lib\libLLVMAsmPrinter.a C:\LLVM\lib\libLLVMCodeGen.a C:\LLVM\lib\libLLVMScalarOpts.a C:\LLVM\lib\libLLVMInstCombine.a C:\LLVM\lib\libLLVMProfileData.a C:\LLVM\lib\libLLVMObject
  .a C:\LLVM\lib\libLLVMBitReader.a C:\LLVM\lib\libLLVMMCParser.a C:\LLVM\lib\libLLVMTransformUtils.a C:\LLVM\lib\libLLVMipa.a C:\LLVM\lib\libLLVMAnalysis.a C:\LLVM\lib\libLLVMTarget.a C:\LLVM\lib\li
  bLLVMCore.a C:\LLVM\lib\libLLVMXCoreAsmPrinter.a C:\LLVM\lib\libLLVMMCDisassembler.a C:\LLVM\lib\libLLVMMC.a C:\LLVM\lib\libLLVMXCoreInfo.a C:\LLVM\lib\libgtest.a C:\LLVM\lib\libLLVMSupport.a image
  hlp.lib psapi.lib shell32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"E:/llvmlite-0.6.0.dev/ffi/build/Release/llvmlite.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DY
  NAMICBASE /NXCOMPAT /IMPLIB:"E:/llvmlite-0.6.0.dev/ffi/build/Release/llvmlite.lib" /MACHINE:X86 /SAFESEH  /machine:X86 /DLL llvmlite.dir\Release\assembly.obj
  llvmlite.dir\Release\bitcode.obj
  llvmlite.dir\Release\core.obj
  llvmlite.dir\Release\initfini.obj
  llvmlite.dir\Release\module.obj
  llvmlite.dir\Release\value.obj
  llvmlite.dir\Release\executionengine.obj
  llvmlite.dir\Release\transforms.obj
  llvmlite.dir\Release\passmanagers.obj
  llvmlite.dir\Release\targets.obj
  llvmlite.dir\Release\dylib.obj
  llvmlite.dir\Release\linker.obj
libLLVMSupport.a(CommandLine.cpp.obj) : fatal error LNK1143: invalid or corrupt file: no symbol for COMDAT section 0xE3 [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
Done Building Project "E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj" (default targets) -- FAILED.

Done Building Project "E:\llvmlite-0.6.0.dev\ffi\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.


Build FAILED.

"E:\llvmlite-0.6.0.dev\ffi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj" (default target) (3) ->
(ClCompile target) ->
  C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throw
s an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  E:\llvmlite-0.6.0.dev\ffi\core.cpp(8): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details. [E:\llvml
ite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  E:\llvmlite-0.6.0.dev\ffi\dylib.cpp(27): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details. [E:\llv
mlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throw
s an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  E:\llvmlite-0.6.0.dev\ffi\executionengine.cpp(74): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for detail
s. [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/ADT/IntrusiveRefCntPtr.h(180): warning C4800: 'llvm::sys::fs::detail::DirIterState *const ' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.d
ev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throw
s an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Value.h(411): warning C4800: 'unsigned int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(454): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Function.h(461): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/IR/Metadata.h(902): warning C4291: 'void *llvm::MDNode::operator new(size_t,unsigned int)' : no matching operator delete found; memory will not be freed if initialization throw
s an exception [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  C:\LLVM\include\llvm/ADT/APInt.h(1530): warning C4244: 'return' : conversion from 'const uint64_t' to 'unsigned int', possible loss of data [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  E:\llvmlite-0.6.0.dev\ffi\transforms.cpp(117): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]
  E:\llvmlite-0.6.0.dev\ffi\transforms.cpp(133): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning) [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]


"E:\llvmlite-0.6.0.dev\ffi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj" (default target) (3) ->
(Link target) ->
  libLLVMSupport.a(CommandLine.cpp.obj) : fatal error LNK1143: invalid or corrupt file: no symbol for COMDAT section 0xE3 [E:\llvmlite-0.6.0.dev\ffi\build\llvmlite.vcxproj]

    27 Warning(s)
    1 Error(s)

Time Elapsed 00:00:30.34
Traceback (most recent call last):
  File "ffi\build.py", line 112, in <module>
    main()
  File "ffi\build.py", line 102, in main
    main_win32()
  File "ffi\build.py", line 65, in main_win32
    subprocess.check_call(['cmake', '--build', build_dir, '--config', config])
  File "C:\Python34\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'E:\\llvmlite-0.6.0.dev\\ffi\\build', '--config', 'Release']' returned non-zero exit status 1
error: command 'C:\\Python34\\python.exe' failed with exit status 1

E:\llvmlite-0.6.0.dev>
```

I don't know anything that can cause this error , please help

Thanks.

**Comment by pitrou** [comment]
According to Microsoft, "This error can be caused if the object file is corrupt". First check if your disk may be full (or any other failure that may lead to such an error). Also, please try to remove the "ffi\build" directory and then build again.
