### ISSUE TITLE
ctypes TypeError on emitting object

### ISSUE THREAD

**Issue by DecrepitHuman** [numba/llvmlite#847]
After initializing a few things:
```python
binding.initialize()
binding.initialize_all_targets()
binding.initialize_all_asmprinters()
```
And then creating a target machine to then emit a module as a object:
```python
target = binding.Target.from_tripe(self.module.triple)
machine = target.create_target_machine(opt=opt)

with open(out, "wb") as file:
    file.write(machine.emit_object(self.module))
    
# Code to clean stuff
...
```

I get no errors from parsing the ir and verifying it, however when calling `machine.emit_object(self.module)` I get the following ctypes error:
```
Traceback (most recent call last):
  File "\\wsl$\Ubuntu\home\nicholas\IdeaProjects\Jewel\generator.py", line 46, in compile
    file.write(machine.emit_object(self.module))
  File "C:\Users\Nicholas\AppData\Roaming\Python\Python310\site-packages\llvmlite\binding\targets.py", line 286, in emit_object
    return self._emit_to_memory(module, use_object=True)
  File "C:\Users\Nicholas\AppData\Roaming\Python\Python310\site-packages\llvmlite\binding\targets.py", line 305, in _emit_to_memory
    mb = ffi.lib.LLVMPY_TargetMachineEmitToMemory(self, module,
  File "C:\Users\Nicholas\AppData\Roaming\Python\Python310\site-packages\llvmlite\binding\ffi.py", line 151, in __call__
    return self._cfn(*args, **kwargs)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_LLVMModule instance instead of Module

Process finished with exit code 1
```

To clarify, `self.module.triple` is `x86_64-unknown-linux-gnu` with `opt` being the integer `2`. `self.module` is a instance of `llvmlite.ir.Module`
The IR I am using in this example is:
```
target triple = "x86_64-unknown-linux-gnu"
target datalayout = ""

@test = internal constant i32 0
```

**Comment by DecrepitHuman** [comment]
Fixed, this was due to a problem on my part. I needed to pass it a `ModuleRef` instance and not `Module`
