### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#885]
As title.

**Comment by esc** [comment]
Ref: #869

**Comment by esc** [comment]
@seyong92 llvmlite 0.39.1 does not support Python 3.11.

You can track the Numba issue here: https://github.com/numba/numba/issues/8304 -- Numba and llvmlite versions that support Python 3.11 will be released at the same time, hopefully soon.

**Comment by sklam** [comment]
Python 3.11 is supported since merging of #869

**Comment by vricosti** [comment]
Yes same issue here I cannot install open-whisper using poetry, I am using the following env:

MacOS Monterey
Python 3.11.2 (brew install python@3.11)
Poetry 1.4.1
```
• Installing llvmlite (0.39.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/Users/jdoe/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/jdoe/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/jdoe/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/y5/s2l5hw0s74vdk9k54krfs2zc0000gn/T/tmpbvb330w3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/y5/s2l5hw0s74vdk9k54krfs2zc0000gn/T/tmpbvb330w3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/y5/s2l5hw0s74vdk9k54krfs2zc0000gn/T/tmpbvb330w3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/y5/s2l5hw0s74vdk9k54krfs2zc0000gn/T/tmpbvb330w3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 55, in <module>
    File "<string>", line 52, in _guard_py_ver
  RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
```

**Comment by esc** [comment]
> Yes same issue here I cannot install open-whisper using poetry, I am using the following env:
> 
> MacOS Monterey Python 3.11.2 (brew install python@3.11) Poetry 1.4.1

@vricosti llvmlite 0.39.1 does not support Python 3.11 -- the 0.40.0 release is currently being prepared, this will support 3.11

**Comment by wookayin** [comment]
Install the rc version building from source:
```
pip install 'llvmlite @ git+https://github.com/numba/llvmlite/'
```
You will need LLVM 11, make sure `llvm-config --version` gives 11.x. On Ubuntu 20.04:

```
sudo apt install llvm-11-dev
sudo update-alternatives --install /usr/bin/llvm-config       llvm-config      /usr/bin/llvm-config-11   200
```

**Comment by rjurney** [comment]
This got me too, Poetry 1.4.2 on Ubuntu 20.04 with `graphistry[ai]` and Python 3.10.10.

**Comment by esc** [comment]
> Until the official release, try installing the rc version by building from source:
> 
> ```
> pip install 'llvmlite @ git+https://github.com/numba/llvmlite/'
> ```
> 
> You will need LLVM 11, make sure `llvm-config --version` gives 11.x. On Ubuntu 20.04:
> 
> ```
> sudo apt install llvm-11-dev
> sudo update-alternatives --install /usr/bin/llvm-config       llvm-config      /usr/bin/llvm-config-11   200
> ```

In general we discourage users from using system level LLVM packages as outlined here:

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#what-to-be-aware-of-when-using-a-system-provided-llvm-package

You can also use the RC now, the llvmlite wheel has a satic LLVM< embedded, so you don't need to install that with `apt`.

**Comment by esc** [comment]
> This got me too, Poetry 1.4.2 on Ubuntu 20.04 with `graphistry[ai]` and Python 3.10.10.

This is a different issue. You are on Python 3.10  so things should "just work". If you are having poetry issues, try cleaning the cache. We often see issues with poetry and llvmlite and it usually boils down to cleaning the poetry cache.
